### ISSUE TITLE
Disable/Enable themeing

### ISSUE THREAD

**Issue by sobi3ch** [Bash-it/bash-it#1001]
> AKA leave my `PS1` alone!

First of all, great project! :+1: 
But (please correct me if I'm wrong) why there is no option to disable PS1 theming for good. I've try to comment out `BASH_IT_THEME` and reload it but obviously this didn't helped me. If there is solution for that already then please add this info to bash* config variables 
```
..
# Lock and Load a custom theme file
# location /.bash_it/themes/
# You can turn off theming by commenting 
# out and realoding settings with `reload` command
export BASH_IT_THEME='bobby'
..
```

There could be question during installation process as well.

**Comment by nwinkler** [comment]
Thanks for the nice feedback!

To answer your question: There is no option for disabling themes because nobody asked for that feature so far 😄 

Here's how this could be done:

In https://github.com/Bash-it/bash-it/blob/master/bash_it.sh#L53, place an `if` block around the following lines:

```bash
# Load colors first so they can be used in base theme
source "${BASH_IT}/themes/colors.theme.bash"
source "${BASH_IT}/themes/base.theme.bash"

# appearance (themes) now, after all dependencies
source $APPEARANCE_LIB
```

These lines load the theme, so putting them inside an `if` would allow to skip them.

For the `if` condition, do the following:

* Define a variable at the top of the file, e.g. like this: https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash#L2 - name it something like `BASH_IT_USE_THEME`
* Make sure to use a value if the user provides one, otherwise use `true` as a default.
* In the `if` condition, check for the value of `BASH_IT_USE_THEME`

This way, it will continue to work for existing users without breaking any functionality, and will allow you to run Bash-it without a theme. You simply need to set the `BASH_IT_USE_THEME` variable to `false` in your `~/.bashrc` before loading Bash-it.

Please feel free to create a PR for this. Don't forget to add documentation for the new variable...

Looking forward to your contribution.

**Comment by udondan** [comment]
I haven't found where it is called but something is making use of the function `safe_append_prompt_command` which is defined in the theme files. So beside disabling above mentioned lines I had to add a dummy function:

```bash
function safe_append_prompt_command {
  :
}
```

I already have my styled prompt, just interested in the autocomplete featue. 😸

**Comment by nwinkler** [comment]
Good one! One way of fixing this would be to move the definition of the function to one of the base libraries, e.g. `helpers.bash`. If it's used outside of the themes, it shouldn't depend on the themes to be loaded - that's clearly an error.

**Comment by nwinkler** [comment]
I grepped the code, but could not find a location where the `safe_append_prompt_command` function was called outside of the themes - usage seems to be isolated to the themes...

**Comment by udondan** [comment]
Yeah, that's really strange. That's what I meant yesterday with _I haven't found where it is called_. I also grepped the codebase and could only find it in the themes. I must have been stupid yesterday, because today it's not barking anymore w/o the dummy function. 🤷‍♂️ 

I sent a PR for this feature. Though instead of introducing a new var, like you suggested above, I'm checking if the `$BASH_IT_THEME` is empty. Let me know if that's alright with you.

**Comment by nwinkler** [comment]
👍 Merged and closed - thanks a lot!

Greetings from Westbahnhof!
