### ISSUE TITLE
bash-it causes problem for gitserver

### ISSUE THREAD

**Issue by emptymalei** [Bash-it/bash-it#1032]
I installed bash-it on my server which hosts my git repos. Then I found that any remote pull or push from other machines returns the error message

```
fatal: protocol error: bad line length character: Plea
fatal: The remote end hung up unexpectedly
```

Uninstallation of bash-it solved the problem.

**Comment by nwinkler** [comment]
It looks like Bash-it tries to respond with some kind of error message on new connections - I suppose you're seeing this with SSH connections from a Git client, right?

Can you please try to log in using a standard SSH client into the server to see what Bash-it is trying to complain about? It's probably a message about a dependency that was not found or something like that.

If you get a result there, please post it here. We have tried to eliminate such messages from happening, since they interfere with all kinds of software (e.g. `scp`), but it looks like this one slipped through.  I bet it's the beginning of "Please do this or that to bla bla bla" 😄 

Let me know what you find and we'll get this fixed.

**Comment by emptymalei** [comment]
Here are more details about this error.

The server has Ubuntu 16.04LTS installed. I installed bash-it through the git clone and install.sh method provided by the READEME file.

I am pulling/pushing on a Mac with macOS Sierra. 

>  I suppose you're seeing this with SSH connections from a Git client, right?

Not sure what you mean. I did all these in iTerm2, with zsh shell.

-----

In summary, the plugins that are causing trouble are `nvm` and `fasd`.

-----

I also figured out it's about the plugins. Tried to enable and disable them to figure out which ones exactly.

If I enable `chruby` and `chruby-auto`, I got these

```
fatal: protocol error: bad line length character: Bash
/home/me/.bash_it/plugins/enabled/250---chruby-auto.plugin.bash: line 4: /usr/local/share/chruby/chruby.sh: No such file or directory
/home/me/.bash_it/plugins/enabled/250---chruby-auto.plugin.bash: line 5: /usr/local/share/chruby/auto.sh: No such file or directory
/home/me/.bash_it/plugins/enabled/250---chruby.plugin.bash: line 4: /usr/local/share/chruby/chruby.sh: No such file or directory
```

Then I enabled all the plugins and tried to disable them from the last one.

The message without `chruby*` stuff is

```
fatal: protocol error: bad line length character: Bash
```

I went all the way back up and I got a change in the message until I got to `nvm` plugin.

```
fatal: protocol error: bad line length character: You
/home/lei/.bash_it/plugins/enabled/250---go.plugin.bash: line 8: go: command not found
```

Then I diabled `go` plugin,

```
fatal: protocol error: bad line length character: You
```

Finally I figured out the last one which is `fasd`.

**Comment by nwinkler** [comment]
In general, you should only enable plugins that you intend to use, and for which you have installed the required dependencies. If you don't have the `chruby` tool installed, you should not enable the `chruby` or `chruby-auto` plugins. One could argue that the plugins should check for dependencies and then fail silently if the dependencies are not found - Pull Requests to fix these are more than welcome...

To be safe, disable all plugins and only enable what you really want to use.

The comment about the SSH connections was with regards to the "remote pull or push from other machines" that you wrote in your original post. When you use the `ssh:` protocol to connect to the Git repo, an SSH connection is opened, which opens a shell session on the server, which then runs through the `~/.bashrc` file, which in your case seems to load Bash-it and then fails with an error message. You probably would not see this error if you used `http://` or `https://` for connecting to the Git server to push/pull. I'm not asking you to use HTTP(S) instead of SSH, just a comment...

**Comment by emptymalei** [comment]
@nwinkler I got it. Thank you for the explanation. 👍  

It's pretty safe to close this issue I guess.

**Comment by nwinkler** [comment]
Thanks for closing this. Can you please summarize which plugin was causing the issue? I saw nvm and fasd in your post, but also the chruby ones. Anything else?

**Comment by emptymalei** [comment]
@nwinkler `chruby`, `chruby-auto`, and `go`.

I knew from the error message that these three responded with error simply because I haven't installed them. So I didn't include them in my original reply. 
I learned from your reply and just realized that I do not have nvm and go either. So this is not bug at all.
