### ISSUE TITLE
Cannot launch my scripts

### ISSUE THREAD

**Issue by TuTPhoto** [Bash-it/bash-it#1061]
Hi all,
I am very new to bash-it
I understood I can place all my own script in my $HOME/.bash-it/custom to have them available.
I am using OpenSuse 42.3 linux with Bash but cannot understand how to use this feature.
I also added in my .bashrc file the directive
export BASH_IT_CUSTOM="/home/hidden/.bash-it/custom"
I cannot find precise instructions or a wiki or some more instructions on Google
Thanks!
Maurizio

**Comment by nwinkler** [comment]
What are you trying to achieve? Can you share an example of a custom script that you want to load?

The common use case is to define your own set of aliases, and then place the file with these aliases in the `custom` folder.

Another use case is to have custom functions in a file in the `custom` folder. Bash-it will then `source` this custom file and your custom functions will be available in your shell.

What's the content of your custom scripts? Please post an example here and we can then discuss what to do with the script...

**Comment by TuTPhoto** [comment]
In data lunedì 16 ottobre 2017 20:38:50 CEST, Nils Winkler ha scritto:
> What are you trying to achieve? Can you share an example of a custom script
> that you want to load?
> 
> The common use case is to define your own set of aliases, and then place the
> file with these aliases in the `custom` folder.
> 
> Another use case is to have custom functions in a file in the `custom`
> folder. Bash-it will then `source` this custom file and your custom
> functions will be available in your shell.
> 
> What's the content of your custom scripts? Please post an example here and
> we can then discuss what to do with the script...
Hi Nils,
thank you for your very fast reply.
In my $HOME/bin folder I have some scripts I usually use to run.
IN bash-it readme I read: 
Bash-it provides a solid framework for using, developing and maintaining shell 
scripts and custom commands for your daily work. If you're using the Bourne 
Again Shell (Bash) on a regular basis and have been looking for an easy way on 
how to keep all of these nice little scripts and aliases under control, then 
Bash-it is for you! Stop polluting your ~/bin directory and your .bashrc file, 
fork/clone Bash-it and start hacking away.
So I thought bash-it can help to archive and manage own shell scripts.

For example I use the following scripts to backup a photo archive using lftp

#!/bin/bash
PgmName="Drive Syncro"
WrkDir=/home/user/bin/lftp

#Chiedo conferma all'utente
kdialog --title "$PgmName" --yesno "Vuoi procedere con \
la sincronizzazione dell'archivio FTP?"

#Verifico la risposta (1=NO)
if [ $? = 1 ]; then
	exit
fi

# Se la risposta è affermativa (0=SI) lancio il comando di sincronizzazione 
avvisando l'utente
kdialog --title "$PgmName" --passivepopup "Avvio sincronizzazione..." 5;
lftp -f $WrkDir/command &> $WrkDir/syncro.log
kdialog --title "$PgmName" --msgbox "La sincronizzazione è terminata!"

# Se il file di log non è vuoto chiedo all'utente se vuole visualizzarlo
if [ ! -s $WrkDir/syncro.log ]; then
        echo "Nessuna modifica registrata..." > $WrkDir/syncro.log
	exit
fi

kdialog --title "$PgmName" --yesno "Vuoi visualizzare \
le modifiche fatte?"

#Verifico la risposta (1=NO)
if [ $? = 1 ]; then
	exit
fi

kdialog --title "$PgmName" --textbox $WrkDir/syncro.log 500 800

How can I remove if from $HOME/bin and 'integrate' in bash-it?

Thank you,
Maurizio

**Comment by nwinkler** [comment]
Ah, yes, now I understand. You have a couple of standalone scripts in your `~/bin` folder and you want to manage them using Bash-it. Here are a couple of options:

* The scripts are standalone files at the moment, they run when you call them. To use them with Bash-it, you would have to convert the above sample script into a Bash `function`. Please take a look at the files in the `plugins/available` folder to see what these look like. All of your above code needs to go into a function within a `.bash` file. Once you place that file into the `custom` folder and open a new shell, the function will be loaded and sourced into the current shell session. So if your function was called `backup-photos` for example, you could then call `backup-photos` from your current shell session and the function would run.
* Instead of placing the function into a file in the `custom` folder, you could also create a real plugin that contains the function. The work is the same as above, you need to convert your script into a function, then place it inside of the `plugins/available` folder instead of the `custom` folder.

Please note that I don't know whether calling something like `kdialog` is going to work from a function, I have never tried that.

Does this make sense?

**Comment by TuTPhoto** [comment]
Good morning!
Now it is all more clear.
As soon as @ home I will try and post the results.
Thank you again,
Maurizio

2017-10-17 8:27 GMT+02:00 Nils Winkler <notifications@github.com>:

**Comment by nwinkler** [comment]
Thanks for confirming - closing now.

**Comment by TuTPhoto** [comment]
In data martedì 17 ottobre 2017 09:39:12 CEST, Nils Winkler ha scritto:
> Closed #1061.
Hi all,
just for the records, now all works smoothly!
Also the external command kdialog.

Thank you,
Maurizio

**Comment by nwinkler** [comment]
Thanks for confirming - glad to hear that it's working now! Happy bash-ing!
