### ISSUE TITLE
Strange wrapping issues

### ISSUE THREAD

**Issue by drawcard** [Bash-it/bash-it#1125]
Hi, I am having this problem with bobby & powerline-plain themes for bash-it. As you can see when I cd into a directory or resize terminal, the command prompt gets completely messed up:

![kapture 2018-01-03 at 23 42 03](https://user-images.githubusercontent.com/1435638/34521955-519169e4-f0e0-11e7-9883-31dcffefff47.gif)

Specs:
![image](https://user-images.githubusercontent.com/1435638/34521980-711cc948-f0e0-11e7-88bd-e9e374627fdf.png)

**Comment by drawcard** [comment]
More oddities 🤔 

**Initial state**
![image](https://user-images.githubusercontent.com/1435638/34522514-e3f0780a-f0e2-11e7-883f-c87ab8d34d4d.png)

**Resizing window**
![image](https://user-images.githubusercontent.com/1435638/34522601-4ba857ec-f0e3-11e7-9fe8-207630994d8e.png)
![image](https://user-images.githubusercontent.com/1435638/34522617-5e99ca70-f0e3-11e7-92db-9d84f6a33644.png)

**Comment by nwinkler** [comment]
Looks great - I really dig the repetitive nature! 😄 

Has this worked with a previous version of macOS, and the issue started with High Sierra?

I'm asking since I've seen a similar issue with Terminal.app and High Sierra with the `powerline-multiline` theme. I think there was a change with the window width of the Terminal window starting with High Sierra.

I fixed this in my fork in the following commit (for the `powerline-multiline` theme): https://github.com/nwinkler/bash-it/commit/08aa0f11e1996bf41a510c48f29b23b70e91713c#diff-6f2eb4f167d9a2bac63edca751037459

Not sure if you're seeing a similar issue, but it might be connected. I have not had time to provide a clean fix for the issue I had seen, that's why it's only in my fork so far...

**Comment by nwinkler** [comment]
And I can recreate your issue with the `powerline-plain` theme - resizing the window causes the issue:

![_bash_it_ _-bash_ _bash_ _94x40](https://user-images.githubusercontent.com/907063/34523054-0e63e31c-f096-11e7-8ea3-203987af379d.png)

**Comment by drawcard** [comment]
Cool, I thought it was just me going crazy :)

As far as I know the problem has only appeared in High Sierra (haven't used bash-it yet in another OS) but I may try out iTerm2 and see if that does the same thing.

**Comment by drawcard** [comment]
iTerm2 seems to have the same issues but at least you can keep typing into the prompt without having characters wrap all over the PS1 area, so it's semi-usable: 
![kapture 2018-01-08 at 14 06 26](https://user-images.githubusercontent.com/1435638/34658223-3dbffd22-f47d-11e7-9abc-067518669216.gif)

**Comment by drawcard** [comment]
Quick update, I decided to reinstall bash-it as follows and it cleared up most of my problems:

```rm -rf ~/.bash-it/```
Then clone the bash-it repo as per README (but I didn't run install.sh, as I wanted to keep my config file.

The only problem that lingers is lines of text garbling up when the terminal is re-sized (it's an issue I can tolerate for the time being though). 

![image](https://user-images.githubusercontent.com/1435638/35134733-37178252-fd28-11e7-97ac-5df7636110d6.png)

**Comment by nwinkler** [comment]
Thanks for the update!

**Comment by bulldozier** [comment]
We recently solved a similar issue and the root cause was a bad value for the locale. The locale was getting set to "C" (ancient, no unicode support). That locale treats every byte as a character. But modern locales like utf8 have 2-byte characters. It doesn't actually have anything to do with Powerline other than the fact that Powerline uses non-breaking spaces for spaces, which are 2 byte unicode characters. It also uses 2-byte unicode characters for the right-facing triangles in the prompt. For every space or triangle in the prompt, it thinks there are 2 characters instead of 1. This causes all of the strange wrapping behavior.

The fix is to make sure your locale is correct.  See [what-does-lc-all-c-do](https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do) for information about LC_ALL. For us, glibc was actually the culprit. For some good info on how glibc uses the locale, see: [differences-between-en-us-utf8-and-en-us-utf-8](https://superuser.com/questions/999133/differences-between-en-us-utf8-and-en-us-utf-8).

**Comment by bulldozier** [comment]
Our use model was a bit different since we are running Centos in Docker. Our fix was the following:

In Dockerfile:
-ENV LANG=en_US.UTF-8
+ENV LANG=en_US.utf8
+sed -i 's/UTF-8/utf8/' /etc/yum.conf

Then we ran "locale -a" and "locale" to verify that en_US.utf8 was there. When we used the capital letter form (UTF-8), it was getting set to "C" which caused the bad wrapping.

**Comment by bulldozier** [comment]
BTW if glibc is built with the wrong locale, you'll need to rebuild it. For Centos/RH, that means running   "yum reinstall glibc-common" after fixing /etc/yum.conf.
