### ISSUE TITLE
Error when using ssh host autocomplete

### ISSUE THREAD

**Issue by dimitrov-adrian** [Bash-it/bash-it#1219]
using ssh autocomplete causing error

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

it doesn't matter if `ssh ` or `ssh example` just when pressing [tab]

OS: macOS HS
Ver: Current git SHA: e4df64b on 2018-07-19T09:10:17+02:00

**Comment by nwinkler** [comment]
This should have actually been fixed with this commit: https://github.com/Bash-it/bash-it/commit/e23d26c8fe95911ec3b0c2ce1121ac3be6b02b4f

The fix was provided with #1217.

Can you please ensure that you have run a `bash-it reload` after downloading the latest version? It's possible that you're still using the old completion code if you haven't run `bash-it reload` - or open a new Terminal window/tab, which should definitely load the current code...

**Comment by dimitrov-adrian** [comment]
@nwinkler confirm after reload, it fixed. Thanks

**Comment by nwinkler** [comment]
Thanks for confirming - glad that it's working now!
