### ISSUE TITLE
Custom aliases completion only working after bashit reload

### ISSUE THREAD

**Issue by diegonz** [Bash-it/bash-it#1299]
I have noticed that my custom aliases work as expected, but they are not autocompleted at all until I run `bashit reload` *(or `bashit update`)*.

For example, with the following alias defined in *custom.aliases.bash*:
- `alias aptpolicy='apt policy '`

When I type `aptpolicy apac` and hit <kbd>TAB</kbd>, I expect to receive every *apt packages* starting with **apac** as completion options, but nothing happens.

However, if I run `bashit reload` once I opened the *bash* session, every custom alias completion starts working as expected.

This is happening on *4* different machines running Debian *(1)* and Ubuntu *(3)*.

**Comment by nwinkler** [comment]
Yes, this is the expected behavior (at the moment). As outlined in the [DEVELOPMENT.md file](https://github.com/Bash-it/bash-it/blob/master/DEVELOPMENT.md), custom aliases, completions and plugins are only loaded after all of the other components (including the `alias-completion` plugin).

One way to fix this would be to load custom components first, but then you run into the problem of possibly breaking dependencies, e.g. if a custom plugin references a function from a Bash-it plugin.

I don't think there's a simple way for fixing this, unfortunately. You could of course submit your custom aliases to be included in Bash-it (if they are generic and reusable)...

**Comment by diegonz** [comment]
Ok, thank you very much for the info.

I'll try to solve it by loading some aliases that I need *(like)* with autocompletion before loading `bash_it`.
I think this way is enough for me and probably it will not break anything.

However, I don't discard sending a pull request with some of my generic aliases, and also a theme I've made based on `byobu` *(when I'll have a little time)*.

**Comment by nwinkler** [comment]
Sure, please do - contributions are always welcome. When providing your aliases, please try to group them logically or add them to existing alias files where it makes sense.
