### ISSUE TITLE
bash: _filedir: command not found

### ISSUE THREAD

**Issue by dimitrov-adrian** [Bash-it/bash-it#1305]
When completing (with tab) docker or docker-compose, I get error

```
bash: _filedir: command not found
```

OS: macOS Mojave
Bashit: Current git SHA: 7a5b797 (but it also happend with previous versions)

**Comment by dimitrov-adrian** [comment]
Thanks @nwinkler

Installing bash-completion from brew do the trick. It will be good if can works without it, or at least not throwing such error.

**Comment by nwinkler** [comment]
Good point! Here's the thing: From what I remember, the completions in question (docker, docker-compose) were copied over from the original Bash completions at one point, hence the dependency on the Bash-Completion OS package. Once you have installed Bash-Completion and the `system` completion Bash-it component, you shouldn't need to use Bash-it's `docker` and `docker-compose` completions, since they will be redundant.

Please take a look in Homebrew's root folder to see the existing completions that come with Homebrew. For me, they are in `/usr/local/etc/bash_completion.d`. If you installed Docker and Docker-Compose through Homebrew, it should have included the Bash completion files for the tools.

Realistically, we should try to get rid of the Bash-it completion files that were copied from the Bash Completions of the OS packages, since they add bloat, are probably outdated, and cause maintenance and support issues. If people would consistently use the `system` completion, we shouldn't have to shadow these completions files in Bash-it.
