### ISSUE TITLE
Any method of exporting a bash-it configuration to another machine or ditfile repo?

### ISSUE THREAD

**Issue by pard68** [Bash-it/bash-it#1350]
I have been using bash-it for a week or two now and I like it a lot. Takes a lot of prior work I did myself and streamlines it. One thing I have noticed, or have not yet figured out, is how to move my personal bash-it config (including theme, active plugins, aliases, etc.) from one machine to another. My current workaround is to just make a tarball, copy it over with rsync and then untar it on the other machine. In the long term this is a problem. I looked through historic bash-it issues and didn't see any mention and I tried to look through documentation, code, and just `ls` through the bash-it dir to see if such a config file or export feature exists. 

I thought about just pointing my local bash-it at my fork of the project but that seemed less than elegant. Additionally, I would like to have some method of adding bash-it to my ditfile repo without having to use a submodule.

Any chance this issue has been tackled or there already exists a method to do what I want to do? If not, and it sounds like something that would be appreciated, I don't mind taking on the issue.

**Comment by nwinkler** [comment]
Good question! You are right, there is no standard way of doing this at the moment. Various people have asked for this functionality and there have been a couple of attempts at adding something like this to Bash-it, but no solution has emerged from this.

Having said that, here's how I do this:
* My Bash profile is part of my dotfiles repo, this includes the theme setting: https://github.com/nwinkler/dotfiles/blob/master/home/.bash_profile
* I have a custom script each for home and work, including some additional settings that only apply for home or work, e.g. like this: https://github.com/nwinkler/dotfiles/blob/master/home/.bash_home - these are linked into `$BASH_IT/custom` respectively.
* My Bash-it config (aliases, completions, themes) are backed up by a custom script that I created. It iterates over the enabled items and then creates a self-contained script that includes the list of enabled items and the code to apply the configuration. Here's the backup script: https://github.com/nwinkler/dotfiles/blob/master/home/bin/backup-bash-it
And here's one of the generated backup files, this one is for work: https://github.com/nwinkler/dotfiles/blob/master/bash_it_config_work.sh

The way the backup file is created was done to help with diffing versions of the file, so you can see which aliases/completions/plugins were added or removed. The script then first disables all components and only enables the ones that are listed in the backup file.

I thought about adding this to Bash-it, but decided against it due to time constraints, having to add documentation, etc. - let me know if you find this helpful.

Please let me know if you have questions...

**Comment by pard68** [comment]
Thanks, let me run through these. The backup file you create looks a lot like how I envisioned the config file. I'll give this a go when I get home.

**Comment by meatware** [comment]
i work in devops and often have to move between different machines, which i try to clearly distinguish    by different coloured prompts. i use this function to copy my setup via rsync to remote machines.

https://github.com/meatware/custom_bashrc/blob/5f016709ceab7662b9c9619602ea64ff61635b99/bashrc_assets/_bash_colour_functions.sh#L108-L112.

hope it is helpful!

**Comment by drmikecrowe** [comment]
I use [dotphiles](https://github.com/dotphiles/dotphiles) and add my default `bashrc` config [like this](https://github.com/drmikecrowe/dotphiles/blob/master/bash_it/bash-it.sh).

~/.bashrc:
```bash
source ~/.dotfiles/bash_it/bash-it.sh
```

**Comment by davidpfarrell** [comment]
Here's the simple script I devised to export the components as a series of `enable` commands:

*bashit-backup.sh*:
```bash
#!/usr/bin/env bash

source "${BASH_IT:?"variable not defined"}"/bash_it.sh

components=( alias plugin completion )

echo "# Bash-it Enabled-Component Backup"
echo "# Date: $(date)"
echo "# Folder: ${BASH_IT}"
echo "# Components: ${components[@]}"
for component in ${components[@]}; do
	echo ""
	echo "# ${component}"
	echo ""
	echo "#bash-it disable ${component} all"
	echo ""
	for feature in $( bash-it show "${component}" | grep '\[x\]' | awk '{print $1}' | sort ); do
		echo "bash-it enable ${component} ${feature}";
	done
done
```

Here's the output from a backup I just created:

*bashit-restore*:
```bash
# Bash-it Enabled-Component Backup
# Date: Tue Nov  5 10:10:00 PST 2019
# Folder: /Users/david/.bashit-fork
# Components: alias plugin completion

# alias

#bash-it disable alias all

bash-it enable alias docker
bash-it enable alias docker-compose
bash-it enable alias general
bash-it enable alias git
bash-it enable alias homebrew
bash-it enable alias homebrew-cask
bash-it enable alias osx

# plugin

#bash-it disable plugin all

bash-it enable plugin alias-completion
bash-it enable plugin base
bash-it enable plugin dirs
bash-it enable plugin docker
bash-it enable plugin docker-compose
bash-it enable plugin git
bash-it enable plugin go
bash-it enable plugin java
bash-it enable plugin osx

# completion

#bash-it disable completion all

bash-it enable completion bash-it
bash-it enable completion brew
bash-it enable completion docker
bash-it enable completion docker-compose
bash-it enable completion git
bash-it enable completion go
bash-it enable completion makefile
bash-it enable completion maven
bash-it enable completion system
```

The restore file is not self-executable, you have to source it.

You can easily modify the script to make the `disable all` statements active by default.

-DF

**Comment by davidpfarrell** [comment]
Here's the simple script I devised to export the components as a series of `enable` commands:

*bashit-backup.sh*:
```bash
#!/usr/bin/env bash

source "${BASH_IT:?"variable not defined"}"/bash_it.sh

components=( alias plugin completion )

echo "# Bash-it Enabled-Component Backup"
echo "# Date: $(date)"
echo "# Folder: ${BASH_IT}"
echo "# Components: ${components[@]}"
for component in ${components[@]}; do
	echo ""
	echo "# ${component}"
	echo ""
	echo "#bash-it disable ${component} all"
	echo ""
	for feature in $( bash-it show "${component}" | grep '\[x\]' | awk '{print $1}' | sort ); do
		echo "bash-it enable ${component} ${feature}";
	done
done
```

Here's the output from a backup I just created:

*bashit-restore*:
```bash
# Bash-it Enabled-Component Backup
# Date: Tue Nov  5 10:10:00 PST 2019
# Folder: /Users/david/.bashit-fork
# Components: alias plugin completion

# alias

#bash-it disable alias all

bash-it enable alias docker
bash-it enable alias docker-compose
bash-it enable alias general
bash-it enable alias git
bash-it enable alias homebrew
bash-it enable alias homebrew-cask
bash-it enable alias osx

# plugin

#bash-it disable plugin all

bash-it enable plugin alias-completion
bash-it enable plugin base
bash-it enable plugin dirs
bash-it enable plugin docker
bash-it enable plugin docker-compose
bash-it enable plugin git
bash-it enable plugin go
bash-it enable plugin java
bash-it enable plugin osx

# completion

#bash-it disable completion all

bash-it enable completion bash-it
bash-it enable completion brew
bash-it enable completion docker
bash-it enable completion docker-compose
bash-it enable completion git
bash-it enable completion go
bash-it enable completion makefile
bash-it enable completion maven
bash-it enable completion system
```

The restore file is not self-executable, you have to source it.

You can easily modify the script to make the `disable all` statements active by default.

-DF
