### ISSUE TITLE
removed '/tmp/alias_completion-<string>' printed on a new terminals

### ISSUE THREAD

**Issue by aasril** [Bash-it/bash-it#1354]
I'm on Linux Mint 18.3 with `bash 4.4`. What I did first was to update `bash-it`, but it still happened. I tried with `bash 5.0` and the same message was still printed on each new terminal. I hadn't make any changes to my `.bashrc` or `bash-it`. I don't know what triggered the issue.

But what worked for me was to disable and then re-enable `bash-it` completion with this commands:

```
bash-it disable completion bash-it
bash-it enable completion bash-it
```

So, I'm submitting this issue then close it. For documentation purpose, just in case someone else having the same problem.

**Comment by nwinkler** [comment]
Thanks for documenting this!

**Comment by krishnakumarg1984** [comment]
This does not work. I still get ` /tmp/alias_completion-<string>` printed on my new terminals.

**Comment by aasril** [comment]
I did a new installation with Ubuntu 18.04. And the issue happens again but the above solution does not work this time.

**Comment by krishnakumarg1984** [comment]
I have this issue persisting both on my Ubuntu 18.04 & MacOS Mojave 10.14.5

**Comment by NoahGorny** [comment]
@aasril @krishnakumarg1984 are you still encountering this? can you provide more information and screenshots?

**Comment by krillin666** [comment]
I'm on Fedora 32/33 (Gnome) and I've been experiencing the reported issue for about 1.5 months.
I've tried the solution posted in this issue to no avail. I even updated to the dev branch but the printing of removed '/tmp/alias_completion-######" happens every time (note I inserted the "#" symbol to symbolize that every time I start a new shell the characters that appear change like: removed '/tmp/alias_completion-10474g9Y2l', removed '/tmp/alias_completion-10474g9Y2l' .

Thank you for your time.

**Comment by davidpfarrell** [comment]
OK I *think* we have the culprit:

_in [alias-completion.plugin.bash](https://github.com/Bash-it/bash-it/blob/43ef48544d78697e006cbe6fb52ff00762f697f6/plugins/available/alias-completion.plugin.bash#L94)_:
```
source "$tmp_file" && rm -f "$tmp_file"
```

A quick test of `rm` on Ubuntu 18.04:
```
$ docker run --rm -it ubuntu:18.04

root:/# touch /tmp/boo
root:/# rm -v /tmp/boo

removed '/tmp/boo'
```

Its very common for people to create "safe" aliases for `rm` to prevent accidents. i.e something like:
```
alias rm="rm -i -v"
```

`rm -f` will suppress the `-i` but it won't suppress the `-v`, and there doesn't appear to be any kind of `+v` option to force-suppress `-v`

Bash-It doesn't expect to come up against these types of configurations, but since it uses common tools, its bound to happen.

One way to get past this is to invoke the command directly, by-passing any aliases:

```
$ alias rm="rm -i -v"
$ touch /tmp/boo
$ rm -f /tmp/boo

removed '/tmp/boo'

$ touch /tmp/boo
$ command rm -f /tmp/boo
$ ls /tmp/boo

ls: cannot access '/tmp/boo': No such file or directory
```

[`command`](https://bash.cyberciti.biz/guide/Command) invokes a command, bypassing functions and aliases.

Bash-It should probably use this for every command invocation.

@krillin666 , @aasril , @krishnakumarg1984 : Do any of you have time to submit a quick PR to update alias-completion.plugin.bash to use `command rm` ?
