### ISSUE TITLE
Integration with gitstatusd

### ISSUE THREAD

**Issue by romkatv** [Bash-it/bash-it#1378]
This issue is to gauge interest in integrating Bash-it with [gitstatus](https://github.com/romkatv/gitstatus/blob/master/README.md#using-from-bash).

Bash themes normally call `git` commands to obtain information about the current Git repository. This can be slow when working with large repositories and/or using underpowered devices such as Raspberry Pi. [gitstatus](https://github.com/romkatv/gitstatus/blob/master/README.md#using-from-bash) provides an alternative way to extract the same information 10 times faster.

Is this something you would find useful in Bash-it?

**Comment by nwinkler** [comment]
Yes, sure - this would be great! It would have to be optional, of course, with a fallback to the current functionality if gitstatus is not installed.

I imagine we would have a second version of the current prompt functions which use gitstatus instead of the git commands - or an `if/else` in each of the current functions.

Please feel free to provide a PR if you want to see this in Bash-it!

**Comment by markusdd** [comment]
I have worked on a PR for this and in my testing it looks good already. Will provide branch/PR for review today.

**Comment by markusdd** [comment]
PR is in place. Please review/adapt as necessary. #worksforme ;)
