### ISSUE TITLE
When failing to update (bash-it update) error message provides no relevant information

### ISSUE THREAD

**Issue by Niceplace** [Bash-it/bash-it#1410]
After running `bash-it update`, I get the following :

```
ad00b74: Ensure node paths are appended to existing $PATH (Nils Winkler)
93b2443: Remove errors if plugin executable not available (Nils Winkler)
[... more commits] (added by me)

Would you like to update to ad00b74? [Y/n] Y
Error updating Bash-it, please, check if your Bash-it installation folder (/home/simon/.bash_it) is clean.
```

How can I obtain more information of what is happening exactly ?
What does it mean that my bash-it installation folder is "not clean" ?
I tried looking into `helpers.bash`, it seems the error is being handled on line 180.

Is their any way to view the actual error that was triggered ?

**Comment by nwinkler** [comment]
Thanks for reporting this! Here are a couple of hints:

* You've found the right place to look for this in `helpers.bash`. The command that is causing this issue is on line 171: https://github.com/Bash-it/bash-it/blob/ad00b74f4cc5cdfb01ac2660ffcf85306a578f48/lib/helpers.bash#L171
* You can try to see the error message when you go into your Bash-it folder (`/home/simon/.bash_it`) and run the following command:
```bash
git pull --rebase
```
* Before doing that, you might want to run `git status` in your Bash-it folder. You probably have local modifications there that you either need to commit or discard. Please let me know if you need help doing that, in case you're not familiar with Git.

**Comment by Niceplace** [comment]
Thanks so much for the detailed answer ! Appreciate it.
I'm pretty familiar with git, just a bit slow in the head to debug that issue that's all :D !

Yesterday I found out that my SSH key was expired so I fixed that but the error persisted.

`git status` listed that all the files were modified and `git diff` showed a bunch of:

```
diff --git a/.gitattributes b/.gitattributes
old mode 100644
new mode 100755
diff --git a/.gitmodules b/.gitmodules
old mode 100644
new mode 100755
diff --git a/.travis.yml b/.travis.yml
old mode 100644
new mode 100755
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
old mode 100644
new mode 100755
diff --git a/DEVELOPMENT.md b/DEVELOPMENT.md
old mode 100644
new mode 100755
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
```
Makes sense, since I reinstalled my computer recently. Didn't want to lose my config so I just copied the whole bash_it folder.

*Question: Should the permissions be kept to 644 or 755 is OK ?*

I reset everything with `git checkout --` and `bash-it update` succeeded ! :D 
Thanks for the help,

**Comment by nwinkler** [comment]
Thanks - glad to hear that this is working now! The permission change could have happened during copying from the other machine, I guess. Resetting to the original version makes sense...
