### ISSUE TITLE
showing hostname of ssh'd box machine

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#1416]
Is there any possibility the hostname to switch between local machine and other ssh'd boxes. This would be useful to keep track in which box you are ssh'd. How can we configure something like that for the powerline theme?

**Comment by nwinkler** [comment]
Let me try to understand the requirement - is this accurate?

* You run Bash-it with the "powerline" theme on your local machine. It shows your local hostname (e.g. `kirk`) as part of the theme.
* You `ssh` into a remote server/VM (e.g. `spock`). On the remote VM, Bash-it is also installed as part of your Bash configuration, also using the "powerline" theme. In this case, it should show the remote hostname (`spock`), since Bash-it is running on the remote server.

This is the way it works for me, when I have Bash-it on both my local machine and the remote machine. Is this the way you're using this? And are you saying this is not working?

Sorry if I missed something...

**Comment by nwinkler** [comment]
Sorry, can't help with this. In the case you describe, how/where do run the Bash shell in this case? If you `ssh` into a remote machine, isn't that where the shell runs?

**Comment by kirk86** [comment]
> If you `ssh` into a remote machine, isn't that where the shell runs?

Yup, that's where the shell runs, that's why I said that I've seen it work with `ssh -i ....` cause you can get a shell that way and query for the hostname but not with pass since it requires interaction from user. Thought maybe you'd seen sth similar, but it's ok, thanks?

**Comment by nwinkler** [comment]
No, sorry - never used it like that before.
