### ISSUE TITLE
Incorporating Gogh Feature Request

### ISSUE THREAD

**Issue by tad1073-zz** [Bash-it/bash-it#1426]
How would I incorporate [Gogh](https://github.com/Mayccoll/Gogh) into this?

**Comment by nwinkler** [comment]
Good question! I haven't looked into this in detail, but I basically see two things here:

* A `gogh` plugin that loads the tool.
* A `gogh` theme that uses `gogh` for taking over the prompt. Instead of defining the `PROMPT` variable inside of the theme, delegate it to `gogh`.

Does that make sense?

**Comment by tad1073** [comment]
Or you could merge the gogh theme repository into the theme file for this project.

**Comment by nwinkler** [comment]
I would recommend against that, since it introduces licensing and maintenance issues... I'd prefer to keep it as a separate tool, like we do with other external dependencies.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
