### ISSUE TITLE
BASH_IT_CUSTOM doesn't work without setting bash globstar option

### ISSUE THREAD

**Issue by rishid** [Bash-it/bash-it#1435]
Setup:
Setting BASH_IT_CUSTOM in my .bashrc prior to source bash_it.sh 
e.g. `export BASH_IT_CUSTOM=/home/foo/bash_it_custom`

These files are not loaded unless I set globstar option in bash prior to loading bash_it.sh.  Looking at the code it appears that it is using a "**" which requires the globstar option for evaluation.

`bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
`

**Comment by gaelicWizard** [comment]
I was wondering why there were two asterisks there. Is the goal really to recuse to *all* subdirectories and import all *.bash files?

**Comment by NoahGorny** [comment]
I guess this was the original purpose, but I do not think it is really necessary to do it this way, we can change our impl

**Comment by davidpfarrell** [comment]
So bash-it has 3 uses of `**`:

```
bash_it.sh:
CUSTOM="${BASH_IT_CUSTOM:=${BASH_IT}/custom}/*.bash ${BASH_IT_CUSTOM:=${BASH_IT}/custom}/**/*.bash"

completion/available/rake.completion.bash:
recent=`ls -t .rake_tasks~ Rakefile **/*.rake 2> /dev/null | head -n 1`

completion/available/capistrano.completion.bash:
recent=`ls -t .cap_tasks~ Capfile **/*.cap 2> /dev/null | head -n 1`
```

Additionally, bash-it has 0 uses of `set -s globstar`

It _seems_ nice to allow the user to organize their custom bash scripts however they like, especially since their scripts likely existing before they installed bash-it.

If we decide to keep the feature, we should definitely save/et/restore the globstar value.

Additionally, we might want to add save/restore logic to the 2 matching completions?

**Comment by gaelicWizard** [comment]
Setting and unsetting `globstar` seems super hard to get right for completions as those functions get called at any moment and possibly repeatedly in rapid succession, and since _Bash It_ has never enabled it (and the feature doesn't exist on v3.2) it doesn't seem like it's relied on anywhere. 

This actually tripped me up as I have several folders in what is now my `$BASH_IT_CUSTOM` directory and I did *not* expect them to all be traversed and loaded. 

I'd like to suggest that the user's custom folder be treated as an alternative to the main directory, such that component sub-directories are loaded with their brethren (i.e., completions loaded from main and custom in the same loop). This would need changes to `reloader.bash` and probably shouldn't be done until both the profiles work and some future not-user-writable work is done as those are likely to have impact on how this implemented. Does that make any sense?
