### ISSUE TITLE
OpenIndiana Hipster 2019.10: Bash-it shows up just fine in MATE terminal but not over SSH

### ISSUE THREAD

**Issue by jdrch** [Bash-it/bash-it#1454]
Bash version: 5.0.11(1)-release (x86_64-pc-solaris2.11)

Bash-it works in MATE terminal, but when I SSH into the OpenIndiana machine it doesn't. It shows up just fine over SSH for the other machines (Debian 10.2, Raspbian 10, Ubuntu 19.10) I have it installed on.

Is there a separate setting in Bash configs for SSH?

Any ideas? (r/Illumos [discussion](https://www.reddit.com/r/illumos/comments/e531pq/openindiana_hipster_201910_bashit_shows_up_just/))

**Comment by nwinkler** [comment]
Thanks for opening this issue. The reddit discussion pretty much has all the analysis... The issue seems to be that for your OS, the respective file that Bash-it installs in isn't loaded for SSH sessions.

Possible solutions:

* Source the respective file from your shell as described in the reddit thread, or
* Update the Bash-it installer for this specific OS flavor to install into the correct file.

A third alternative would be to work with the OpenIndiana folks to figure out why they handle the Bash configuration files in a different way than other Linux flavors...

**Comment by jdrch** [comment]
> work with the OpenIndiana folks

I emailed the discussion mailing list this morning.

Here's what the shell looks like in MATE:

![Bash-it](https://user-images.githubusercontent.com/1056759/70067797-7043a780-15b4-11ea-9c0a-5ae39ed1d92b.png)

And here's what it looks like over SSH:

![MobaXTerm](https://user-images.githubusercontent.com/1056759/70067869-95381a80-15b4-11ea-8e6e-6d2d1bec65f2.png)

Here's what happens when I `su` over SSH. Bash-it shows up as expected. But when I exit root, Bash-it is replaced by the vanilla Bash shell:

![su](https://user-images.githubusercontent.com/1056759/70067949-b7319d00-15b4-11ea-94d5-ec285cb032b2.png)

**Comment by jdrch** [comment]
@nwinkler I think I'm making some progress: the above may be happening because SSH is a login shell while the MATE terminal is a non-login shell, and in Unix [both types of shells read from different sources](https://www.reddit.com/r/illumos/comments/e531pq/openindiana_hipster_201910_bashit_shows_up_just/f9kj28y/).

For non-login shells, where does `Bash-it` read from if no `~/.bashrc` file exists (OpenIndiana lacks said file)?

**Comment by jdrch** [comment]
Since I've created an issue that gets to the root of this problem (see above), I'm closing this one.
