### ISSUE TITLE
Default jump behavior

### ISSUE THREAD

**Issue by jpmcb** [Bash-it/bash-it#1482]
Hi there!

I'm wondering why the jump plugin was set to `z` and not the default keybinding of `j`? 
https://github.com/Bash-it/bash-it/blob/master/plugins/available/jump.plugin.bash#L6

There was no reference to a non-default keybinding when I entered `bashit show plugins`.
I purpose that bash-it provide a default experience and enable the user (through the custom plugin) to set a different keybinding. If not, this should be documented.

**Comment by davidpfarrell** [comment]
Greetings !

I'm guessing this has something to do with `jump` acting as a drop-in replacement for the the `z` command.

I see on jump's [document homepage](http://gsamokovarov.com/jump/) that `z(1)` is listed as a `"See Also"`

Best I can tell, this is the command being referenced:
* https://github.com/rupa/z
* https://news.ycombinator.com/item?id=4464003 (HN Announcement)

Indeed there is a `z` plugin here in bash-it that is derived from it:
* [plugins/available/z.plugin.bash](https://github.com/Bash-it/bash-it/blob/7c09252ac86f430b9a6eaeebfc19b20a9f6fe3ce/plugins/available/z.plugin.bash)
(although no link to the Z project page appears to be present)

I agree the binding should be more clearly documented.

Additionally, making it configurable seems like a reasonable action.  Not sure if using environment variables, which are used extensively in the themes for user configuration, would work in plugins, or if there is some other established technique that could be used.

-DF

---
A few side notes:
* Looks like the bash-it `z` plugin is deprecated in favor of the `fasd` plugin - Wondering if `jump` should be considered equally as deprecated? (or maybe `fasd` deprecated over jump?)
* I love that the `z` project's readme is its manpage ( uses `groff -man -Tascii`)
* I also love that the `jump` project homepage is its manpage (looks like it uses [ronn](https://github.com/rtomayko/ronn))

**Comment by jpmcb** [comment]
As it stands, the `jump` configuration found in `plugins/available/jump.plugin.bash` is simply initializing the jump binary, which should be already installed. Typically, this would require:
```bash
eval "$(jump shell)"
```
to be placed in a `.bashrc` or `.bash_profile`. However, this is an anti-pattern for bash-it. 

Yes, a user could create a custom plugin for this. I've tested the following and to get the default behavior, all you need is the following file:

`plugins/custom.plugins.bash`
```bash
cite about-plugin
about-plugin 'initialize jump (see https://github.com/gsamokovarov/jump)'

__init_jump() {
  command -v jump &> /dev/null || return

  # note that we use the default behavior here which is the j keybinding
  eval "$(jump shell)"
}

__init_jump
```

This gives the default behavior as expected if jump was installed clean. Regardless, I believe the default behavior for the user should be the `j` keybinding, not the `z` binding.

**Comment by davidpfarrell** [comment]
Looks like the `z` binding was an overlooked component of the initial PR ( #1216 )
* The PR description doesn't mention it (although it does mention  FASD being deprecated)
* The author of the PR ( @adawalli ) didn't mention it
* @nwinkler didn't mention it
* The creator of Jump ( @gsamokovarov ) actually commented on the PR, but also didn't mention the binding.

This was likely because overriding `z` is a common use case for `jump`.

Although `--bind` is the only argument mentioned on the project's homepage, a look into the source code suggests there may be other supported arguments for the tool.

As such, I recommend:
* We remove the hard coded `z` binding
* We add support for a `${JUMP_OPTS}` (or similar) environment variable. ie:
```
eval "$(jump shell "${JUMP_OPTS[@]}")"
```

**Comment by jpmcb** [comment]
Great suggestion. I can work on this if this is the direction we'd like to go!

**Comment by gsamokovarov** [comment]
Hey. thanks for the interest in jump! 😻 The positional argument of `jump shell` is the shell integration. If you miss it, it's autodetected and this can cause problems. So you can do `jump shell bash` to be sure it will produce the bash integration and `--bind` is the name of the shell helper which is `j` by default.

**Comment by davidpfarrell** [comment]
Hi @gsamokovarov ,

So for bash-it, being all, you know, Bash centric, should we consider something like:
```
eval "$(jump shell bash "${JUMP_OPTS[@]}")"
```
?

Thanks for chiming in !

**Comment by gsamokovarov** [comment]
Yeah, I think this is safe. Otherwise, people may end up passing the shell integration option to `jump shell`, which can lead to bad integrations.

**Comment by nwinkler** [comment]
Great discussion! A couple of comments:

- `fasd` seems to be unmaintained, indeed. The last changes were made 4 years ago: https://github.com/clvv/fasd
- The Bash-it `z` plugin seems to be an old copy of the `z` code from https://github.com/rupa/z/blob/master/z.sh, not sure which version... From a licensing perspective, this is questionable.

I'm wondering whether we should try to clean this up a bit. How about the following:

- We remove the `z` plugin file.
- We remove the `fasd` plugin file - @tswicegood are you still using `fasd` - I noticed that worked on the `fasd` plugin file in the past.
- We fix the `jump` plugin as described above, defaulting the key to `j`, providing an option for people to override with their keybinding of choice (`z` for example).

Thoughts?

**Comment by tswicegood** [comment]
Gah, just got hit by this. Hadn't updated in awhile and when I did `z` quit working (I was using it via fasd). I'm not sure I understand why it was removed. Definitely qualified as one of the "if it ain't broke" type things.

I'll dig into Jump and see if it'll work for my purposes. Might be a better experience. 😄 

----

It does look like I'm not the only one [who got bit by this](https://github.com/Bash-it/bash-it/commit/036c26dbed157b210d303efb6c187693f4361ea4#commitcomment-37406263). In the future, we should probably tread a little more lightly on removing things. I'd love to see things follow a deprecation pattern along these lines:

- Add a warning letting people know things are going to go away. Ideally, point them to GitHub issue explaining why and maybe some docs on adding custom functionality to keep it the way it is now.
- Remove functionality, but keep the warning in place for a period of time with new language explaining it was removed.
- After a period of time, remove the warning.

Given how rarely things like shell scripts are updated, I'd love to see each of these steps spread out over a 3+ months each. Or maybe 3 months for the first phase, 6 months for the warning, then remove it. Embarrassingly, it's been more than 3 months since my last upgrade, so I'd have jumped straight to "things quit working and here's why" but that would've been better than getting a random `Unable to read ./enabled/250---fasd.plugin.bash` on startup and having to dig for it.

**Comment by nwinkler** [comment]
Hi @tswicegood - good to see you here again! Sorry if this was causing trouble for you - please see the discussion about the removal above. It looks like `fasd` is no longer maintained, and the `z` code was copy/paste from some other repo...

Regarding deprecation warnings: This is a good point, but I'm not sure whether it can be solved easily. So far, Bash-it has had a policy of not printing any messages if possible, to minimize noise.

There's some more discussion on that here in #1501, maybe take a look there and chime in. Where would you want to see deprecation warnings? Whenever a new shell session is initialized? Or once after updating (which might be more difficult to achieve)?

I agree that we need some functionality like that, but we'll have to take the right approach for this. Feedback/input welcome!

**Comment by nwinkler** [comment]
Folks, `fasd` is back in Bash-it - thanks to @cornfeedhobo, see #1602. The integration is a lot cleaner now. Sorry about thoughtlessly removing it a while ago.

If you're using one of the other tools like `jump` or `autojump`, don't enable all of them at the same time...
