### ISSUE TITLE
sourcing bash-it keep asking for a password

### ISSUE THREAD

**Issue by verajosemanuel** [Bash-it/bash-it#1504]
after fresh clean install and sourcing bash-it for the first time, a dialog keeps asking for a password so I have to open other terminal and kill it

**Comment by nwinkler** [comment]
Can you please provide some more info?

* List of Bash-it plugins, aliases, completions that you enabled during the installation.
* Your Bash profile (`~/.bash_profile`, `~/.bashrc`)
* Your operating system
* A screenshot of the password prompt.

**Comment by verajosemanuel** [comment]
Nothing was enabled yet as it started to fail just on first run.
seems that is messing with my gpg config so I had to remove it

**Comment by nwinkler** [comment]
Sure - let me know if there's anything I can help with.

**Comment by davidpfarrell** [comment]
Could it possibly be related to the `"detecting sudo"` logic?    Does some form of that check execute during startup, even if there are no themes enabled?

**Comment by nwinkler** [comment]
The sudo checks are done as part of the prompt code, so without a theme it shouldn't get executed at all. Even so, the sudo checks should never ask for the password.

Since the original poster (@verajosemanuel) has not provided his Bash profile content, or a screenshot of the password prompt, it's all guesswork at this point...

**Comment by verajosemanuel** [comment]
I had to uninstall it as it was impossible to use terminal. Sorry
