### ISSUE TITLE
How do I set bash-it to update automatically and unattended?

### ISSUE THREAD

**Issue by jdrch** [Bash-it/bash-it#1523]
Ideally I'd like to be able to create a `cron` job that runs `bash-it update` daily. However, I can't find any way to do run that command silently/non-interactively.

Any ideas? Is that even possible?

**Comment by nwinkler** [comment]
Good question! I don't think that's possible at the moment, since the `update` command always asks for confirmation. I can see a couple of options:

* Instead of running `bash-it update`, use `git` commands (e.g. `git pull`) for updating Bash-it. That will require some additional error handling for cases like local modifications, but should be doable.
* Add a _silent mode_ to the `update` command, e.g. `--silent/-s` (similar to the `install.sh` script). The `update` command can be found here: https://github.com/Bash-it/bash-it/blob/2332c9e82e861e60aff8f6c8e8512b235496ff47/lib/helpers.bash#L149

**Comment by jdrch** [comment]
> Add a _silent mode_ to the `update` command, e.g. `--silent/-s` (similar to the `install.sh` script). The `update` command can be found here:

Are you suggesting I do a PR?

**Comment by nwinkler** [comment]
Yes, absolutely! If you want to get this fixed, please feel free to create a PR 😄

**Comment by NoahGorny** [comment]
Fixed in #1626
