### ISSUE TITLE
ng complete no longer exists

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1542]
https://github.com/Bash-it/bash-it/blob/88231867b6bf966ef285534d5aa43bce803cb50d/completion/available/ng.completion.bash#L2

Kindly use the following code
```bash
NG_COMMANDS="add build config doc e2e generate help lint new run serve test update version xi18n"
complete -W "$NG_COMMANDS" ng
```

**Comment by jdrch** [comment]
Will this finally fix the `-bash: ng: command not found` error on login?

**Comment by tbhaxor** [comment]
I have already opened a PR, waiting for @nwinkler to merge it

**Comment by jdrch** [comment]
> 
> 
> I have already opened a PR, waiting for @nwinkler to merge it

Ha, good luck with that. I'm thinking of abandoning this project as it's clearly poorly maintained the dev obviously doesn't give 2 💩s about fixing anything. Anytime you file a request the response is basically "fix it yourself."

**Comment by tbhaxor** [comment]
@jdrch using bashit aint obligatory its. If it seems headache to you better you get rid of it.

**Comment by jdrch** [comment]
> @jdrch using bashit aint obligatory. If it seems headache to you better you get rid of it. 

Did earlier today 👌🙌

**Comment by nwinkler** [comment]
> > I have already opened a PR, waiting for @nwinkler to merge it
> 
> Ha, good luck with that. I'm thinking of abandoning this project as it's clearly poorly maintained and the dev obviously doesn't give 2 💩s about fixing anything. Anytime you file a request the response is basically "fix it yourself." Like sure dude, if I wanted to fix the code myself I'd have just manually customized my bash prompt to begin with 🤦‍♂️

@jdrch Sorry if you feel that way. Just to clear up some things:

* I maintain this project in my free time - I review, fix, and merge things when I have time. This is not my full-time job.
* Open source projects live from the participation of users (the community).
* I respond with "Please file a PR if you have a fix for this" in many cases, since a) I don't have the time to fix all of the issues, and b) often I don't use the tools myself. For this specific example: I don't use the `ng` tool myself - which means that I need to rely on someone who actually uses the tool in question.

Lastly, thanks for the encouraging words, this is why I love open source.
