### ISSUE TITLE
[Question] Receiving the message "There's a dead ssh-agent at the landing..." at first terminal start upong login.

### ISSUE THREAD

**Issue by Fooughhy** [Bash-it/bash-it#1579]
Hi!

I am just wondering what this message means... I am new to linux, and ssh agents are not the most clear thing to me. 
I am using bashit on commit `bae6bb` and ofcourse have the sshagent plugin enabled.

**Comment by nwinkler** [comment]
Great question... I'm not using the `sshagent` plugin, since the SSH Agent is working fine for me on macOS without this plugin. On Linux, this might be different.

The message is from the plugin:

https://github.com/Bash-it/bash-it/blob/941cf71a77546c9904e834a65baf150d357980eb/plugins/available/sshagent.plugin.bash#L97

This line is reached when there's a process ID (PID) in the `~/.ssh/agent-env.${HOSTNAME}` file (which is created during the last run of the plugin), but the process is no longer alive. This could happen after a reboot, for example.

I think it's safe to ignore this message, since the case is quite common, and the plugin handles this case gracefully. We could probably safely remove this `echo` line from the plugin. I'll do that now...
