### ISSUE TITLE
Why change default GREP_COLOR?

### ISSUE THREAD

**Issue by dedowsdi** [Bash-it/bash-it#1600]
Default GREP_COLOR is changed in alias setup, that seems weird.
https://github.com/Bash-it/bash-it/blob/f0dcf698579954bcf10e20c56e658bdcfe5aeb76/aliases/available/general.aliases.bash#L31

I noted this because I use [solarized](https://ethanschoonover.com/solarized/) theme, `1;33` is a grey color. 

I don't see the point of change it from default `1;31` to `1;33`.

It's no big deal, I can change it after source `bash-it`.

**Comment by davidpfarrell** [comment]
Greetings!

It looks like the opinionated `GREP_COLOR` settings has been around since [First Commit](https://github.com/nwinkler/bash-it/commit/9c7cd9aa0078efde2128732bd4fa8bf226b88fae#diff-00eefb511d7c83da6c0e667a78dd13f2R3)

Although my search-fu wasn't strong enough to confirm it, testing locally (Mac) suggests that 1) there is a default color when one is not defined and 2) the mentioned `1;31` is the default color:

<img width="489" alt="grep_color" src="https://user-images.githubusercontent.com/45741407/82155405-a22a8c80-9829-11ea-9f77-f7d732982866.png">

NOTE: I also use a solarized (dark) terminal color scheme.

So it looks like we *could* safely remove this default setting.

**Comment by dedowsdi** [comment]
Hi davidpfarrell

That's weird, `1;33` is the same as `1;93`, it's the 11th ansi color, bright yellow.

 `solarized` use `base00` for the slot in [xresources](https://github.com/brantb/solarized/blob/master/xresources/solarized), it should be gray.

My grep result in urxvt-256color, ubuntu18.04:
![grep](https://i.imgur.com/BVrWPg4.png)

I get similar result in text console (`linux-16color`).

My color palette (I swapped 0-8, 7-12, but it should not matter), I use only ansi 16:
![palette](https://i.imgur.com/Y0IJOlX.png)

By the way, our yellow and orange doesn't look the same, yours looks a bit too bright, not the same as [solarized](https://ethanschoonover.com/solarized/).

**Comment by nwinkler** [comment]
Feel free to open a PR to remove the `general` aliases `GREP_COLOR` variable. Like @davidpfarrell mentioned, this seems to have been part of Bash-it right from the start, not sure why.

**Comment by dedowsdi** [comment]
I sent a pull request #1601.  I'm closing this.
