### ISSUE TITLE
Slow shell since Xcode Version 11.5 removed svn

### ISSUE THREAD

**Issue by arturmartins** [Bash-it/bash-it#1612]
I have xcode version 11.5 (11E608c) installed and now the shell is always slow (if I'm not in a repo directory)

```
→ time $(which svn)
svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.

real	0m0.813s
user	0m0.376s
sys	    0m0.374s
```
Took 0.8 for the command to run!!

```
→ sudo xcode-select --install
Password:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Workaround: install subversion using brew `brew install subversion`

Unfortunately, I don't use subversion (nor mercurial and the like) and I would like to have the possibility to set `SCM_CHECK=False` and set a variable like `DEFAULT_SCM='git'`.

**Comment by davidpfarrell** [comment]
Greetings,

This new X-Code 'feature' has made it apparent that we need to support the ability to explicitly enable/disable individual SCM tools.

I don't have any gelled ideas yet, but I'm thinking something along the lines of:

```
export SCM_DISABLE_SVN=true
```
Since bashit already checks for the existence of the tool's executable, we only need an override in situations where a tool either has a false-executable (like X-Code), or when the tool is present but the user doesn't want it checked (like me, who has SVN installed but would rather bash-it didn't waste time checking it on my dev machine since I mostly use git)

I'll try to peek at the scm code soon and see how difficult something like this might be to implement.

-DF

**Comment by nwinkler** [comment]
The same thing was already discussed here: https://github.com/Bash-it/bash-it/issues/914#issuecomment-631464825

I think we need to add a check for that specific case. If the XCode `svn` command is no longer there, we need to automatically disable the SVN SCM code. We can check for the `The subversion command line tools are no longer provided by Xcode.` text and then act on that.

This clearly is an edge case that need to handle separately, ideally automatically.

If I find some time, I'll look into some code for this. If someone else wants to tackle this, please go ahead.

The disabling of individual SCM systems through environment variables is a different topic, I think.

**Comment by arturmartins** [comment]
Not sure if handling it automatically would be great, because running `time $(which svn)` can take a while: on my machine (which is fairly recent - 16GB ram, 2.2 GHz 6-Core Intel Core i7), it took almost 1 second.

How can it be done automatically in a way that I don't have to pay 1 second every time I run a new shell?

**Comment by nwinkler** [comment]
How often do you open new shells? Is 1 second really that bad? We could still add an env variable to disable checks for SVN, but I think it's important that we have an automatic check that gracefully handles the situation. Otherwise, we'll have more support tickets here, with everybody asking the same question - "Why is my prompt slow?"

**Comment by arturmartins** [comment]
I think is fair to fix it automatically for newbies. However, as a power user, I would rather prefer to be able to deactivate the ones I don't have/want.

In regards to shells, I open very often. Usually, I try to contain each iTerm window per problem (which might have multiple shells, using tabs).

BTW, my bash-it already takes 10s to start :). 7.5s to reload.

**Comment by nwinkler** [comment]
OK, thanks for the additional info - it looks like we should fix this in two separate use cases:
* Detect the "broken" XCode SVN command and disable SVN checks if that was detected.
* Allow to specify which SCM tools to enable/disable. Would you prefer a whitelist or blacklist approach?

The slow startup time is probably due to some of the slower tool integrations - if you use the search, you will find a couple of tickets that have more analysis on this, also scripts that allow you to time the startup times to find the offenders. I know that `nvm` and `npm` used to be rather slow if I remember.

**Comment by arturmartins** [comment]
I would vote for an `allowlist` approach.

Thanks for the info, I will try find the scripts to time what is taking time on my system. I would be glad to share any insights.

**Comment by nwinkler** [comment]
@arturmartins Can you please take a look at #1613 and see if it fixes the slowness? Feedback welcome.

**Comment by arturmartins** [comment]
I did a bit of cleanup of my scripts (I found out that a some seconds where used by my own functions using `$(brew --link [package])` as well as I deactivate lots of plugins, aliases and autocompletes.

Now I'm able to start a new shell within 2 seconds, if I have svn (homebrew version) installed. 

To test the code, I uninstalled svn so that it would fall into the svn provided  by xcode. Unfortunately, with a busy laptop (chrome, zoom, etc), that SVN_EXE check alone can take up to 6 seconds alone to execute.

I'm happy with the PR  #1613 as it solves the problem for the everybody.

It would be great to have a way that bash-it to be more modular and only load the features I want/need. Currently, I'm forced to install svn so that I don't pay that extra time.

**Comment by davidpfarrell** [comment]
@arturmartins, 

If you'd like to avoid having to install SVN, you could probably create your own svn script with something like this:
__/usr/local/bin/svn__
```
#!/usr/bin/env sh
exit 2
```

Lemme know if you try it.

**Comment by nwinkler** [comment]
Yes, something like @davidpfarrell suggested should work.

The other option we discussed above (specifying a whitelist of SCM tools to use) is still open, we should definitely add that. I would love to add that, but will need to find the time. I also want to add unit tests for the broken SVN check...

**Comment by arturmartins** [comment]
@davidpfarrell: That's actually a good and simple idea. Surprising that I didn't came up with that one myself! Thanks :)

> #!/usr/bin/env sh
> exit 2

**Comment by arturmartins** [comment]
> The other option we discussed above (specifying a whitelist of SCM tools to use) is still open, we should definitely add that. I would love to add that, but will need to find the time. I also want to add unit tests for the broken SVN check...

If I have some time in the coming weeks, I might come with some `allowlist` suggestion for SCM.
