### ISSUE TITLE
`THEME_CHECK_SUDO` should be off per default

### ISSUE THREAD

**Issue by rico-chet** [Bash-it/bash-it#1643]
I experienced very slow terminal while using a _powerline_ theme when connected to a flaky network (e.g. in a train running through tunnels) for quite a long time now. Since this issue has been driving me mad, I set up a stable repro and bisected the git history and it turned out that the `sudo` indicator in the theme was to blame.

The indicator works by calling `sudo` each time the powerline is drawn (i.e. a command run by user is finished). I found that `sudo` (tested on Debian 10):
- writes to `/var/log/auth.log` on each invocation
- runs a DNS query on each invocation (as explained [here](https://superuser.com/a/429890))

So, while the first one just spams a log file, the second one can delay terminal for a couple seconds (until the DNS request times out). To reproduce it in a stable way, I used `tc` to set network latency (to e.g. 3 seconds).

After setting `THEME_CHECK_SUDO=false` as described [here](https://github.com/Bash-it/bash-it/blob/master/themes/powerline/README.md#powerline-theme), delays were gone.

My conclusion / suggestion is that due to the side effects mentioned above and the little use the feature provides, it should be off per default.

**Comment by nwinkler** [comment]
Thanks for the analysis! Based on what you found out, I agree, we should probably change this to be disabled by default. There have been several threads about the `sudo` functionality, mostly about the audit log and triggering notifications to a central IT team, but the DNS issue seems to be an additional topic...

If we change this behavior, we need to document that the behavior has now changed - and how to enable it again. The Powerline themes have decent documentation, so that should be doable.

This adds to the discussion about how we want to communicate breaking changes to end users...
