### ISSUE TITLE
Add More Themes from ohmyzsh :D

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1654]
There are plethora of themes in ohmyzsh, can anyone try to include themes from ohmyzsh into bashit please?

**Comment by nwinkler** [comment]
Are you looking for a specific theme, or specific features in one of the themes? Instead of blindly adding more themes (we have plenty already), I'd be interested in understanding which features people are looking for.

The majority of the themes look very similar and only have minor differences from what I have seen. A lot of it comes down to personal preference - maybe we should rather look into features and then make features configurable on themes. The Powerline themes are a good example for this...

**Comment by tbhaxor** [comment]
Yes i do have some themes in my mind, like
+ [bira](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#bira)
+ [bureau](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#bureau)
+ [gnzh](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#gnzh)
+ [oxide](https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes#oxide)

**Comment by nwinkler** [comment]
OK - what makes these themes special? Colors? Features? Other segments that are not in any of the other themes?

(I only had a brief look, but these themes look quite similar to themes that we already have in Bash-it. I'd really like to understand what specifics you're looking for...)

**Comment by tbhaxor** [comment]
@nwinkler i am just obsessed with two liner themes :smile: no particular reason. We already have plenty of two liners but these have different styles (see the second line)

Yes colours are also one of the reason

**Comment by NoahGorny** [comment]
@tbhaxor you are welcome to open PRs with new themes (and documentation about them)
have a great week :smile:
