### ISSUE TITLE
bash: cd: too many arguments

### ISSUE THREAD

**Issue by georgettica** [Bash-it/bash-it#1684]
when opening the terminal with this alias enabled but not installed an error shows up:
bash: cd: too many arguments

when running `bash -x` I found that 
"cd /Users/USERNAME/.bash_it completion --shell=bash"
was the command that caused the crash

maybe there was a collision with aliases but for now I think the error is in
https://github.com/Bash-it/bash-it/blob/c387517122996e1d2619c9331ae23d4ca57bc1c3/completion/available/github-cli.completion.bash#L9

**Comment by NoahGorny** [comment]
great catch!
this happens because `git aliases` is enabled.

https://github.com/Bash-it/bash-it/blob/c387517122996e1d2619c9331ae23d4ca57bc1c3/aliases/available/git.aliases.bash#L118-L120

This causes the check in 
https://github.com/Bash-it/bash-it/blob/c387517122996e1d2619c9331ae23d4ca57bc1c3/completion/available/github-cli.completion.bash#L5
to fail.

#1685 addresses this by checking if `gh` is a binary and not if such name exists
you are welcome to try it and give us a feedback 😄

**Comment by georgettica** [comment]
Will do, thanks for the quick and thorough response!

This case did happen because I a doing some wierd stuff on.my machine but hey, glad I found a bug

**Comment by georgettica** [comment]
commented there, I guess it will be merged soon
