### ISSUE TITLE
Discuss: Requiring new PRs to add their changed files to the clean_files.txt as part of the PR?

### ISSUE THREAD

**Issue by davidpfarrell** [Bash-it/bash-it#1706]
Hi Team,

Wanted to get a discussion started on the idea of requiring users to add their modified files to clean_files.txt as part of a PR?

Actually this may have been the plan all along and I just didn't catch it earlier?

I think its a good idea.

I also think we might be able to add a pre-commit hook that confirms if all the modified files in a commit are present in the clean_files.txt

This could be valuable both in localdev but also in the CI pipeline.

Interested in everyone's thoughts here.

In the meantime, I think I'll put some effort into a pre-commit hook for localdev.

-DF

**Comment by NoahGorny** [comment]
Yes, this was my original plan. We should mark that in the docs as well

I'm against forcing users to add their files, as not all users want to lint their files in their commits, and we should allow them to do so

**Comment by cornfeedhobo** [comment]
I second not wanting to enforce too much on contributors.

Thinking about this now, I'd like to put forward the idea of using someone's self-motivated use of clean_files.txt as an identifier for more people to include as core contributors.

**Comment by nwinkler** [comment]
Yes, that's a great point. In the past, I've asked people politely for adding documentation when they added a new configuration switch, it's a good sign when people follow through with that - shows they care and are willing to make the framework better instead of doing a quick, one-off PR.

**Comment by davidpfarrell** [comment]
Hi Gang, thanks all for chiming in !

Now, I see the end goal of `clean_files.txt` being to work itself out of existence.  This can only happen if we are regularly adding files/folders to it.

Although I can see that my bid for a hard-line on adding files to clean_files is not going to be our path forward, I'd still like to have a process where we at least ask the user to add their file(s) to `clean_files.txt`.

If the user balks at adding them or balks at making the changes from the CI error report, we could then decide on a case-by-case basis how to proceed - Some ideas being:
* Walk the user through the changes, if they're willing to try
* Create a separate PR  that adds the file(s) to clean_files and fixes them, then have the user re-base / re-apply their PR to the newly updated files.
* Forego the clean_files.txt requirement for the PR

Maybe we could devise a basic copy/paste statement that we can easily add as a PR comment as a starting point for talking with the user. OH or maybe a simple PR Comment Bot that post a simple message to the PR when its opened ... hmmm ...  

PR Templates come to mind, too ...

**Comment by cornfeedhobo** [comment]
> Walk the user through the changes, if they're willing to try

I think once they have balked, the conversation is over. We lose contributors and I want to trend the opposite direction. However, if the haven't balked, then yea, this is a great option.

> Create a separate PR that adds the file(s) to clean_files and fixes them, then have the user re-base / re-apply their PR to the newly updated files.

I think opening up another PR, especially while their's is open and they've shown no interest in clean_files, as rude. I don't want to alienate contributors.

> Forego the clean_files.txt requirement for the PR

Assuming they have balked, I really see this as the only option. I've worked with engineers that have coded for 5+ years with git and have never touched rebase. To illustrate the point, it appears that we currently have a PR open where all the commits are being attributed to another user because the person improperly setup their hooks (1708). I really think we need to be sensitive to this reality until the codebase has reached greater uniformity.

@nwinkler This topic of drafting a second PR for the user to look at has me wondering about code contribution licenses (e.g. is making another pr a technical infringement upon the contributor's property). I personally hate the bots that force you to sign some agreement. I've instead moved to having a pull request template that has a html hidden header that says by opening the PR the user is agreeing to forego all claims from that point forward. Maybe it's time to consider this issue too.

**Comment by NoahGorny** [comment]
Added #1728 which should clarify and close this issue. @cornfeedhobo about the agreement- I want to get #512 so all people can use Bash-it with quite mind
