### ISSUE TITLE
Include Freenode channel in docs

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#1710]
I realize not many people use irc, but could the Freenode channel be included as well?

https://webchat.freenode.net/?channel=#bash-it

_Originally posted by @cornfeedhobo in https://github.com/Bash-it/bash-it/pull/1692#discussion_r519894494_

**Comment by nwinkler** [comment]
I must confess that I have not been on IRC for many years... Are people still using this?

When I had added the Gitter channel several years back, I was logged in there and checked the Bash-it channel on a regular basis, but abandoned it after a while since the channel was flooded with Bash shell scripting questions - the signal/noise ratio was really bad there.

Maybe we should remove the Gitter channel and delete the Gitter channel, since I don't see any value in it in its current form. Getting it to a point where it provides value looks like a daunting task to me, unless you want to have someone that deletes messages that are not on topic...

Thoughts?

**Comment by cornfeedhobo** [comment]
@nwinkler I've been logged into freenode irc for over a decade (almost continuously), and it's how I start most of my days, as well as where I go to get professional support. E.g. I don't know how I would have gotten through my last job without the postgres channels. Certainly not as smoothly. Daily active users is around 100k. It's worth even noting that various companies staff employees in popular channels such as CentOS, Puppet, Suse, and a few others that I know of.

You are completely right about signal to noise on Gitter. Just looking there yesterday and it's sorta become a catch-all place for skids to ask about bash basics. I'm massively in favor of removing it.

As for IRC (freenode specifically), the channels for basic bash support and the community to deal with it exist. The wooledge folks? That's where they hang out. People can be forwarded to the proper place and learn more.

That said, I'm the only one that's been in the channel for like 3 years, although someone other than me has gone through the work to register the #bash-it channel (I'm unable to get operator privileges because of this).

**Comment by nwinkler** [comment]
Thanks for the details - like I said, I've been completely oblivious to IRC for a long time, good to hear that it seems to be a valuable medium for support!

Yes, I'm also in favor of removing the Gitter reference, and potentially deleting the existing Bash-it channel there.

We can add a reference to IRC, I don't mind at all - if you're on there and are ready to answer questions, then let's go ahead!

Thanks!
