### ISSUE TITLE
Git ls-files completion not loaded completely

### ISSUE THREAD

**Issue by tbhaxor** [Bash-it/bash-it#1750]
## Expected Behavior
Well thanks to @davidpfarrell for telling about `git ls-files` command #1733 . Before this I wasn't aware of its existence. I request to please add the completion for all the command that are missing in original git completion files

## Current Behavior

When i press tab after `git ls` nothing happens, but when i press tab after `git ls-files --` all the completions for ls-files are being shown

**Comment by tbhaxor** [comment]
Closing bcoz of no reach

**Comment by davidpfarrell** [comment]
I did a bunch of research on this and *thought* I posted it around here somewhere?  I'll recap with the short version.

[Why 'git ls-files' is not shown on tab completion?](https://stackoverflow.com/questions/9883851/why-git-ls-files-is-not-shown-on-tab-completion)

`ls-files` is considered a *"plumbing"* command,  and the completion script excludes plumbing commands by design.

In previous versions of the completion script, the plumbing commands were explicitly configured, so it would be easy-ish to modify the script to stop excluding specific commands:
* [Expand git's autocomplete feature to plumbing commands](https://stackoverflow.com/questions/26798130/expand-gits-autocomplete-feature-to-plumbing-commands)

Reviewing the [Current Completion Script](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) suggests that this is no-longer such an easy task.
