### ISSUE TITLE
Latest pyenv versions require different initialisation

### ISSUE THREAD

**Issue by SwampFalc** [Bash-it/bash-it#1882]
The latest versions of pyenv no longer support the initialisation commands that are currently used in the plugin.

Error message upon starting a new terminal:

```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

## Expected Behavior

- Using the pyenv plugin should work without error message.
- The shims folder is no longer in PATH.

## Current Behavior
Error message. No shims in PATH.

## Possible Solution
Hard to say... The fix in and of itself is simple, but I do not expect it to be backwards compatible. So anyone that updates bashit but not their pyenv would end up with the inverse problem.

Fix: use `pyenv init --path` instead of `pyenv init -`

## Steps to Reproduce
1. Update pyenv following https://github.com/pyenv/pyenv#upgrading
2. Open a new terminal

## Your Environment

* Bash-it version used: latest
* pyenv version used: also latest (1.2.27-41-gddf952ab)

**Comment by cornfeedhobo** [comment]
Well that's a bummer. I'll try to take a look this weekend.

**Comment by SwampFalc** [comment]
Looking at it, I think https://github.com/pyenv/pyenv/pull/1920 is probably the place with the most explanations about what's happening, why and what their plans for the future are.

**Comment by davidpfarrell** [comment]
Thanks for reporting this !

So changes like this one have been a long-time-coming since you're not _really_ supposed to modify the `$PATH` variable within `.bashrc`, which is where these types of evals usually live.

I have an idea for dealing with this particular instance:

The devs have made the `pyenv init --path` effects transparent here:

* https://github.com/pyenv/pyenv#advanced-configuration

> Sets up your shims path. This is the only requirement for pyenv to function properly. You can do this by hand by prepending `$(pyenv root)/shims` to your `$PATH`.

With this transparency, we have permission to manually add the shims folder to our path, ie something like:
```
eval "$(pyenv init -)"
# In case we're using a new pyenv, manually add the shims to the path 
# pathmunge will safely abort if the path entry is already present
pathmunge "$(pyenv root)/shims" before
```

This could be a one-line fix that gets us past the issue for now ...

**Comment by SwampFalc** [comment]
That approach sounds more backwards compatible.
However, I do believe the order should be reversed. Since `pyenv init -` rehashes the shims, I suspect it might need the shims folder in the path already.

**Comment by davidpfarrell** [comment]
> Since `pyenv init -` rehashes the shims, I suspect it might need the shims folder in the path already.

Doh!, yes that is correct.

An issue with setting the path first is that pyenv doesn't check the path before generating the new path statement (verified locally), so if the shims folder is already on the path, will be added to the path again ... perhaps not a terrible issue but less than ideal.

So, reversing the order could be a quick-fix while we work on a better one.

I suspect we'll need multiple plugins with some kind of tag in the name to distinguish them ...

**Comment by cornfeedhobo** [comment]
> So changes like this one have been a long-time-coming since you're not really supposed to modify the $PATH variable within .bashrc, which is where these types of evals usually live.

I think by this logic, bash-it should move everything to `.bash_profile`. While I think there is a strong argument for that, it's outside the scope of this issue.

> ```eval "$(pyenv init -)"```

The issue is that it now echos the warning on every terminal start.

> so if the shims folder is already on the path, will be added to the path again ... perhaps not a terrible issue but less than ideal.

Funny enough, this concern is how we got into this mess. They didn't want [shims added multiple times](https://github.com/pyenv/pyenv/issues/1649), so `--path` is intended for `.bash_profile`, but there is a coverage gap compared with `init - bash`:

- completion is no longer sourced
- pyenv shims aren't rehashed
- pyenv is no longer a command wrapping the script, which breaks `pyenv shell` (and possibly others)

### My $0.02

- redirect the current init to stdout
- pathmunge the shims manually
- [open an issue on pyenv to add a --completion flag](https://github.com/pyenv/pyenv/issues/1941)

**Comment by cornfeedhobo** [comment]
I've deleted my last comment because it was too long and not accurate. Instead, I've opened a PR that solves the problem, and will follow up with any discussion there. Thanks @SwampFalc & @davidpfarrell !
