### ISSUE TITLE
dnf aliases cause ambiguous redirect with help subcommand in Fedora 35

### ISSUE THREAD

**Issue by wallon-ines** [Bash-it/bash-it#2046]
Hello,

If I want run this command  ` bash-it help plugins`, I have this error: 
```
please wait, building help...bash: $grouplist.$group: ### ambiguous redirect

quiet               what *does* this do?
usage               disk usage per directory, in Mac OS X and Linux

battery:
battery_charge      graphical display of your battery charge
battery_percentage  displays battery charge as a percentage of full (100%)

composure:
cite                creates one or more meta keywords for use in your functions
draft               wraps command from history into a new function, default is last command
:cat: '/tmp/grouplist.VHNdCz.|': No such file or directory
cat: groups: No such file or directory
cat: '|': No such file or directory
cat: grouperase: No such file or directory
cat: '|': No such file or directory
cat: groupinfo: No such file or directory
cat: '|': No such file or directory
cat: groupinstall: No such file or directory
cat: '|': No such file or directory
cat: grouplist: No such file or directory
cat: '|': No such file or directory
cat: groupremove: No such file or directory
cat: '|': No such file or directory
cat: 'groupupdate)': No such file or directory
```
This problem appear if enable dnf's aliases and I don't know enough about this code for create a new PR.

## Step to reproduce

- Adduser test
- Install bash-it
- Run `bash-it help plugins`, result : No errors
- Enable dnf aliases `bash-it enable alias dnf`
- Reload bash-it `bash-it reload`
- Re run `bash-it help plugins` and I see this error
- If I run `all_groups` I see : 
![Screenshot from 2022-01-16 15-24-22](https://user-images.githubusercontent.com/11542186/149663973-04c63632-33d5-4605-a4ad-41b845def763.png)

**Comment by davidpfarrell** [comment]
Hi @wallon-ines thanks for taking a minute to report your issue.

Looking at:
* The [dnf.aliases](https://github.com/Bash-it/bash-it/blob/e06066c36768ac08a31927646a150a6e66badbfc/aliases/available/dnf.aliases.bash) file
* The [_help-plugins](https://github.com/Bash-it/bash-it/blob/c81c9dcc8c0487fa2a550b4ba2aa083982faa679/lib/helpers.bash#L978) function
* The [dnf docs](https://dnf.readthedocs.io/en/latest/command_ref.html#group-command) for the group command
* The [dnf bash completion](https://github.com/rpm-software-management/dnf/blob/565ccbba0869f0400cb85c4e90e2b26494b01fa6/etc/bash_completion.d/dnf#L251) function

I believe the issue stems from this code in the bash completion script:

_function \_dnf()_
```
case "$command" in
    ...
    group|groups|grouperase|groupinfo|groupinstall|grouplist|groupremove|groupupdate)
    ...
```

Although the source code has no spaces between the options, when reformatted via `typeset -f` (used in the plugin helper), bash adds spaces:
```
$ typeset -f _dnf

    ...
    group | groups | grouperase | groupinfo | groupinstall | grouplist | groupremove | groupupdate)
    ...
```

The spacing ends up causing this line to match our `metafor group` metadata extractor, used in the helper function (and in the `all_groups` function):
```
$ typeset -f _dnf | metafor group

| groups | grouperase | groupinfo | groupinstall | grouplist | groupremove | groupupdate)
```

This gets assigned to the `$group` variable in the helper function, then causes problems when used later in the function:
```
        _letterpress "$about" $func >> $grouplist.$group
        echo $grouplist.$group >> $grouplist
```

*NOTE*: At this time, I think its pure coincidence, and not related to the issue, that the helper function creates and uses a variable named `grouplist` :
```
    typeset grouplist=$(mktemp -t grouplist.XXXXXX)
```

And, although I'm confident the issue related to the bash completion function, its not clear to me how/why the issue relates to the enabling/disabling of the dnf aliases.

Perhaps our alias-completion logic somehow invokes the bash completer when it might otherwise not have been active?

@wallon-ines Could you do a test with a fresh session with the aliases _disabled_, confirming `bash-it help plugins` works, then try to invoke the dnf bash completions (i.e try some dnf commands pressing tab to complete the options), and then try `bash-it help plugins` again?

**Comment by gaelicWizard** [comment]
We've just merged a complete overhaul to the alias completion code. Could you (a) give it a try, (b) let us know if it changes anything with these errors?

**Comment by NoahGorny** [comment]
closed as no response was given
