### ISSUE TITLE
Moving chat to another place

### ISSUE THREAD

**Issue by EmilySeville7cfg** [Bash-it/bash-it#2078]
What about to move chat to Discord/Telegram/Gitter or a similar place? Is it any reason to use Libera chat? 🤔

**Comment by gaelicWizard** [comment]
If it gets moved, I would vote for moving to GitHub discussions. External services are just not helpful in this context imho.

**Comment by EmilySeville7cfg** [comment]
I like this idea. (GitHub discussions)

**Comment by gaelicWizard** [comment]
I don't think this is urgent, but I'd love to switch to GitHub Discussions at some point if the @bash-it team are on-board? Many of the issues opened are just questions. I've even got a few open questions that nobody has looked at 😉.

CC: @cornfeedhobo, @NoahGorny, @davidpfarrell

**Comment by NoahGorny** [comment]
Hi @EmilySeville7cfg and @gaelicWizard 
I have created GitHub discussions space, let me know what you think :)

**Comment by EmilySeville7cfg** [comment]
Nice work. 😄

**Comment by cornfeedhobo** [comment]
Hey, I see I'm late to the game, but at least wanted to reply.

@EmilySeville7cfg libera chat was chosen because it's the defacto place for most opensource projects. e.g. puppetlabs and ansible still staff support in their channels, twitter and facebook used to run some of their ops on libera's precursor freenode. It's just wrapped in history.

@gaelicWizard I agree. Discussions is ready for the big time, and seems like the right move.

@NoahGorny all over it as usual. thanks :)
