### ISSUE TITLE
Question: How to disable theme in the same shell; or, is there a good theme for using with the 'script' utility?

### ISSUE THREAD

**Issue by boldandbusted** [Bash-it/bash-it#2093]
How can I disable the Bash-It theme in the same shell session. Is there a good theme for using with the 'script' utility?

## Expected Behavior
* Ability to disable the theme by setting BASH_IT_THEME="", or...
* Suggestion for theme that makes a 'good', 'more readable' output file from the 'script' utility

## Context

Right now, if I run 'script', I get a file with a ton of terminal escape codes and artifacts. I'd like to eliminate this, or at least reduce the cleanup chore.

I've tried to naively set `export BASH_IT_THEME=""` and even `unset BASH_IT_THEME`, but my nice powerline-multiline theme persists.

I wish I could. :) Thank you in advance for any and all suggestions. :) I love Bash-It.

**Comment by davidpfarrell** [comment]
Greetings!

A super-quick way to create an basic shell would be:
```
$ bash --noprofile --norc
```

BUT what I do, in order to allow myself to easily test themes or run with no theme, is:

_~/.bash_profile_
```
# Leave empty to disable theming.
# see: ${BASH_IT}/themes/
: ${BASH_IT_THEME=powerline}
```

So I get `powerline` by default, but I can do this:
```
$ BASH_IT_THEME="" bash -l
```
To get a fresh login shell with no theme enabled.

You can also use this with:
```
$ BASH_IT_THEME="" bash-it restart
```

Hope that helps - give it a try and let us know how it goes!

**Comment by boldandbusted** [comment]
Thank you! Makes great sense. :)
