### ISSUE TITLE
Test battery_percentage with upower fails randomly

### ISSUE THREAD

**Issue by NoahGorny** [Bash-it/bash-it#2104]
see [link](https://github.com/Bash-it/bash-it/runs/5413700302?check_suite_focus=true)
it seems like sometimes we get a broken pipe, even without echoing twice..

What do you think @gaelicWizard ?

**Comment by gaelicWizard** [comment]
I *think* that _Bash_ has a bug with handling `SIGPIPE` sometimes, but I think that this may work with `echo "$BAT0"$'\n'"/path/to/$RANDOM" so that it's one write. I have that somewhere in another branch I'm trying out. 

I suspect that `trap '' PIPE` may alsö work (install a signal handler, but empty), but I'm reluctant to do any signal handling within BATS without lots of care.

**Comment by gaelicWizard** [comment]
Seems my attempt at `echo` was part of #2061 and doesn't work. I've added a conservative application of `trap '' PIPE` to #2031, which seems good so far...

**Comment by gaelicWizard** [comment]
Ok! New PR #2105 fixes this testing error by avoiding the closed pipe entirely.
