### ISSUE TITLE
Problem when $HOME has a space in it

### ISSUE THREAD

**Issue by pacanukeha** [Bash-it/bash-it#343]
If your user name has a space in it the install script chokes.

**Comment by ben-efiz** [comment]
Are you on Mac OS? Because on Linux based OS i think you can't add user names with space. But it's actually not only the user name but the whole $HOME path which could also have spaces and so the install.sh script can have issues, e.g.

cp -a $HOME/$CONFIG_FILE $HOME/$CONFIG_FILE.bak

That would be easy to fix, but then you have all the aliases/completion/plugins making use of the $HOME variable, too! Some of them are actually space save, some aren't. I will suggest a pull request for that.

**Comment by ben-efiz** [comment]
@nwinkler if you or someone else wants to find places where $HOME is uesed without quotation, the following grep command can help

grep -v '\"$HOME' * -Rn | grep '$HOME'

Pretty sure there are more sophisticated versions using patterns to correctly find everything :)

**Comment by nwinkler** [comment]
Thanks, @ben-efiz!

I would change it to the other way around:

    grep '$HOME' * -Rn | grep -v '\"$HOME'

This way, it's selecting all lines containing $HOME first, and then filtering out the ones that don't use quotes. Same result, but should be a bit faster/more efficient.

Using this, I found 33 lines - they probably need to get fixed.

**Comment by nwinkler** [comment]
BTW: Pull Requests are welcome :smile:

**Comment by ben-efiz** [comment]
True and good reminder to have everything optimized on github :) If you execute the following command it filters out the */enabled/* directories, so it shouldn't be much stuff remaining (at least with my config symlink where also part of the result set):

grep '$HOME' * -Rn --exclude-dir=*/enabled/* | grep -v '\"$HOME'

Only two things where i am not sure if quoting $HOME doesn't break anything:

themes/duru/duru.theme.bash:17:  pwd|rev|awk -F / '{print $1,$2}'|rev|sed s_\ _/_|sed "s|$(sed 's,\/,,'<<<$HOME)|~|g"

themes/hawaii50/hawaii50.theme.bash:172:    RELATIVE_PWD=${PWD/#$HOME/\~}

Can you say something about the syntax there?

**Comment by nwinkler** [comment]
Good question...

I'm not familiar with these themes and don't know whether they are still in use by anyone. You're right, the syntax looks strange there - I would leave them as they are until someone complains about them not working...

**Comment by edubxb** [comment]
Thanks @ben-efiz!
