### ISSUE TITLE
Move from gh to hub, the new official GitHub CLI

### ISSUE THREAD

**Issue by edubxb** [Bash-it/bash-it#392]
The project [gh] (https://github.com/jingweno/gh) has been adopted as the new official [GitHub CLI (hub)](https://github.com/github/hub).

See this: https://github.com/github/hub/issues/475

So it is necessary to update:

plugins/available/gh.plugin.bash
completion/available/gh.completion.bash

**Comment by thedrow** [comment]
Don't we have completion for hub?
I think we should keep gh for the time being for those who did not update.

**Comment by edubxb** [comment]
The completion file is basically the same for gh and hub, the command name has changed and some minor changes, I think.

Now hub is in a release candidate state, so we can do the update when finally released.

Additionally, we can add an alias to maintain compatibility (`alias gh=hub`)

**Comment by thedrow** [comment]
But what if I still have gh installed and not hub?
The plugin will fail.

**Comment by edubxb** [comment]
Another option is to have separate plugins+completion, one for gh, and other for hub.

**Comment by nwinkler** [comment]
Wouldn't it be easier to detect whether the `gh` or `hub` command is available? 

```
command -v gh >/dev/null 2>&1 && eval "$(gh alias -s)"
command -v hub >/dev/null 2>&1 && eval "$(hub alias -s)"
```

Same for the completion.

If there's a chance that you want to have both `gh` and `hub` installed, one of them will have to have a higher priority, since you can't alias them both to `git`.

If the differences are significant, I agree that it would be better to have two different plugin/completion files. If it's just the name of the command, it should be possible to detect which one is installed and then alias that.

**Comment by tswicegood** [comment]
:+1: for detecting where we can.  FWIW, I use `hub`, so I wouldn't want to do anything that messes with that.

**Comment by edubxb** [comment]
Done in PR https://github.com/Bash-it/bash-it/pull/562
