### ISSUE TITLE
"which: no drush in" everytime I launch the terminal

### ISSUE THREAD

**Issue by yassargo** [Bash-it/bash-it#480]
After I installed Bash-IT I get the following message when I launch terminal:

which: no drush in (/usr/local/bin:./node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/nginx/sbin:/home/wawa/.local/bin:/home/wawa/bin)

**Comment by nwinkler** [comment]
This is probably caused by the `drush` completion: https://github.com/Bash-it/bash-it/blob/master/completion%2Favailable%2Fdrush.completion.bash#L10

The highlighted line should make a check to verify that the completion is only enabled if the `drush` executable is available - not sure why you are seeing that message.

I've just made a change to the check, please pull the latest version from `master` and verify whether it works for you now.

If not, you can simply disable the completion by running

```bash
$ bash-it disable completion drush
```

Let me know if the change fixes it for you...

**Comment by yassargo** [comment]
That worked. Thanks for the quick response.

**Comment by nwinkler** [comment]
Thanks for reporting back!
