### ISSUE TITLE
New feature - Installation with config file

### ISSUE THREAD

**Issue by TCMiranda** [Bash-it/bash-it#490]
Hello!

Congratulations for the job, awesome framework!

Is it something that you're planning? Make the installation via configuration file of which plugin, alias or completion to include / enable?

If so, i'll be glad to help!

Thanks!

**Comment by nwinkler** [comment]
There has been a previous discussion on this a while ago, going in a similar direction: #126 

Something like this would be nice...

I could imagine that the `bash-it enable/disable` commands creates/updates a file that keeps track of your currently enabled features. You could add this file to your personal dotfiles (e.g. through https://github.com/technicalpickles/homesick) and then reuse it for new installations.

I'm currently using a shell script that I manually update for keeping track of the features that I use: https://github.com/nwinkler/dotfiles/blob/master/bash-it-enable.sh - an automated solution with a config file would be a lot nicer...

**Comment by TCMiranda** [comment]
Yes, that's pretty nice

For example, oh-my-zsh has an interesting way of enabling plugins:
Only adding an array to the .zshrc

    plugins=(git bundler osx rake ruby)

Its simple, but portable and pure bash.

I think that the way that the plugins are enabled / disabled, by creating an link to the 'enabled' folder, is actually enough. dont you think?

We can keep track of what is enabled by listing the "enabled" folder. If we add some way, like zsh, to define enabled plugins and validate the files in the enabled folder at load, it would be easy tell to users to just adjust their variable "plugins=(... ...)" and everything is automatically loaded.

Same for aliases and completions.

For the installation, my idea would be allowing an "--config file" argument, which is file containing arrays, like zsh, enable those plugins, and then copying the file as "~/.bash-it/config" (or something like that). 

    plugins=(git ... ruby)
    aliases=(git ... ruby)
    completions=(git ... ruby)

If the user changes the file "~/.bash-it/config", at load, we validate the array and the plugins enabled.

What you think?

That way we keep things bash only.

**Comment by nwinkler** [comment]
That sounds like a good plan! So do you see us creating a `~/.bash_it_rc` to keep track of these things? I wouldn't create the file under the `~/.bash_it` folder, since it will get messy with the git ignore rules, adding it to your dotfiles, etc.

**Comment by TCMiranda** [comment]
Yes, that's a good point.
In my opinion, a good feature.

So, may I start it?

1. Use a .bash_it_rc at installation
2. Update the file on enable / disable plugins, alias and completions
3. Validate the file on load, listing the "enabled" folder

**Comment by nwinkler** [comment]
One thing to keep in mind is that we should try to keep the startup as quick as possible. Opening a new shell/tab in your terminal app should be quick, I'm not sure whether it's a good idea to verify the enabled/disabled items every time.

We could start with a separate command like `bash-it install` or `bash-it verify` (the `bash-it` command already supports the enabling/disabling). If people want to do this on every start of a new shell, they could still run this command as part of their `.bash_profile`. You can still call it manually if you changed something and don't have it included in your ´.bash_profile`.

Go ahead and take a stab at this, sure...

**Comment by TCMiranda** [comment]
Hey @font, sorry i'm outdated, not working on this anymore. 
If you want to finish it, my work is here: https://github.com/Bash-it/bash-it/pull/494

**Comment by adoyle-h** [comment]
Looking forward to the feature. 😃

**Comment by jalmansor** [comment]
Hmmm... I've been thinking about how to tackle this as well, though more so in keeping my installs in sync.

**Comment by gerardbosch** [comment]
Hi there! It should be necessary to be able to store bash-it configuration (enabled plugins and so on) in a way that can be tracked by a dotfiles repository; so that you can replicate your bash-it setup in a new machine/user account just by cloning/installing your dotfiles repository.

I find the way Zsh does it (by defining enabled settings in ~/.zshrc) is effective and portable, and fits great with a user dotfiles repository. Bash-it should provide a way to easily achieve the same.

N.B. I'm evaluating [homeShick](https://github.com/andsens/homeshick) right now, which is a purely bash reimplementation (with changes) of Homesick (so no Ruby dependencies), and trying to include bash-it as a Git submodule in my dotfiles repo.

**Comment by nwinkler** [comment]
@gerardbosch I had tried to use Bash-it as a Git submodule with Homesick initially, but gave up on this approach pretty quickly. Part of the reason was that I'm making changes in Bash-it frequently, and that did not work well as a Git submodule.

FWIW, I'm backing up my Bash-it config in a script file as part of my dotfiles:

* [Here's the backup script that I'm using](https://github.com/nwinkler/dotfiles/blob/master/home/bin/backup-bash-it), run it like this: `backup-bash-it home` - and it will generate a file like the following.
* https://github.com/nwinkler/dotfiles/blob/master/bash_it_config_home.sh - I can track this in my dotfiles, and run it when moving to a new machine.

Changing the approach that Bash-it uses for tracking enabled components would mean that we move from symbolic links in the `enabled` directory to a file-based configuration. This would be feasible, but would involve a lot of work...

**Comment by nwinkler** [comment]
(Lastly, I have to say that I'm not really fond of either Homesick or Homeshick (tried both). The tracking works fine, but moving to a new machine is painful, since linking the files from Homesick castle to my home folder is complex - I had some major issues with linking directories. In some cases, the tools deleted existing files, I'm really careful with this now. Neither of the tools handled this the way I expected it. Might be user error, but it was a frustrating experience nonetheless.)

**Comment by NoahGorny** [comment]
we shall continue on #1350
