### ISSUE TITLE
-bash: book: command not found

### ISSUE THREAD

**Issue by 7immy** [Bash-it/bash-it#521]
After installing bash-it I get this in my terminal window.
`-bash: book: command not found`
I can't find any reference to it online so I don't know how to fix it.

Any help would be great,
thanks :)

**Comment by nwinkler** [comment]
I have not found any reference to this `book` command in Bash-it.

When installing Bash-it, which options did you select (aliases, completions, plugins)? Did you choose to enable all of them? If so, you might want to disable some of them (or all of them) to see where the issue came from. I have not been able to find any reference to a `book` command in the Bash-it codebase...
