### ISSUE TITLE
opening current working directory with sublime not working

### ISSUE THREAD

**Issue by mtin79** [Bash-it/bash-it#522]
hi there,
it seems like a couple of integrations of native mac apps are not working any more.
e.g.: opening the current working directory in sublime is not working any more:

... some directory i have a project in ...
$ sublime .

is just opening an empty window in sublime.
previously it opened a new window with all containted files in sublime.

also kaleidoscope and tower mac apps have problems now.
is there a general procedure how i can get them get back to work?
otherwise i may need to uninstall bash-it again.

thanks for help and support!

**Comment by nwinkler** [comment]
When you say _previously_, what do you mean? Before installing Bash-it? Or with a previous version of Bash-it, or with a previous version of Sublime?

Bash-it does not have any functionality specific to Sublime - I'm not sure what you mean.

Also, can you be a bit more specific with regards to the other apps? "... have problems now" is pretty vague...

**Comment by mtin79** [comment]
hi nils,
yes these problems appeared after i installed bash-it.

so first problem i encountered was that rvm's files (.ruby-gemset, .ruby-version) where not recognized any longer when changing into a directory. (manage to get it back working when i disabled a bash-it plugin called "fasd".

next thing is that when i want to open a direcoty with $ sublime . in the command line it's not working any longer ...

before i go into details of other apps i guess it's related to what bash-it changed for previous native mac that hook into the command line ...

is there a place in general that i could look into regarding bash-it configuration and installation?
otherwise would uninstalling bash-it revert everything back to how it worked before?

i am not a super user on the command line that's why i am a bit in the dark on how bash-it works and where and how i could get things back working again.

thanks for any help!

**Comment by nwinkler** [comment]
Thanks for the updated info! The first step I would take is disabling all plugins, completions and aliases, and then only enabling the most basic ones. Please run this:

```bash
bash-it disable plugin all
bash-it disable completion all
bash-it disable alias all
bash-it enabled completion bash-it
```

Then close the shell window and open a fresh shell/terminal window. Try your ruby tools and Sublime from the fresh window. The issues might have been caused by a plugin or an updated Path.

**Comment by mtin79** [comment]
Thank you nils,
your help definitely worked!
no i will start looking into what each plugin is about to do and change.
can you point me to any kind of resource to learn what bash-it does and how it does it?

and if it's only the nice command prompt i keep it for ... totally worth it :-)

**Comment by nwinkler** [comment]
Thanks for the feedback - good to hear! You're welcome!

For the command prompt, check out the `powerline-multiline` theme - it's fantastic.

With regards to the plugins/aliases/completions: Only enable the ones that you really need. If you're not using Subversion for example, don't enable any of the Subversion plugin/completion/aliases, and so on.

In general, Bash-it loads the enabled resources through regular shell commands (`source`). Each enabled file is sourced into the current session, and all of the file's commands are executed. By convention, the `alias` files define aliases, the `completion` files enable Bash completion for a certain command, and the `plugin` files are used for everything else (functions, environment variables, PATH settings, ...).

To get started, take a look at one of the plugins that you're using. Since you mentioned Ruby and RVM, start with those...

All of the loading is done from the `bash_it.sh` file.

**Comment by mtin79** [comment]
Thanks Nils, very helpful again!

**Comment by nwinkler** [comment]
You're welcome!
