### ISSUE TITLE
Hub Completions Don't Work

### ISSUE THREAD

**Issue by outdooricon** [Bash-it/bash-it#541]
I have hub completion enabled and gh plugin disabled, but I don't get an completions for hub. I also have git completions enabled. I'm not really sure where to start as far as reporting. This is osx 10.10.4

**Comment by nwinkler** [comment]
Can you provide an example of what you're trying to do? Like showing what you're typing, when you're hitting the Tab key, what the expected outcome is, and what the actual outcome is...

**Comment by outdooricon** [comment]
`→ hub pull`, **expected tab result**: `→ hub pull-request`, **actual tab result**: nothing, stays on prompt
`→ hub pull-request,` **expected tab result**: unsure, maybe historical auto-complete,  **actual tab result**: nothing, stays on prompt
`→ hub pull-request -b dev`,  **expected tab result**: `→ hub pull-request -b develop`, **actual tab result**: nothing, stays on prompt
also tried replacing `hub` with `git` and no result

**Comment by nwinkler** [comment]
OK, had a look. It looks like the current version of Bash-it only supports the older `gh` command, not the newer `hub` one. That's probably the reason why the completion for the `hub` command is not working.

If you take a look at the `gh.completion.bash` file, you'll notice that it only sets up completion for the `gh` command, not for `hub`.

See #392 for a discussion on this topic.

@tswicegood @edubxb @thedrow - any update on using `hub` instead of `gh`? Pull Requests welcome...

**Comment by thedrow** [comment]
I'll try to provide a pull request over the weekend.

**Comment by outdooricon** [comment]
woot, thanks @thedrow !

**Comment by edubxb** [comment]
Fixed in PR #562, please, disable the gh plugin and completion and enable it for hub.

**Comment by outdooricon** [comment]
Thanks guys, this is perfect!

**Comment by edubxb** [comment]
:smile:
