### ISSUE TITLE
$PATH not getting reset during reload (maybe boxen specific)

### ISSUE THREAD

**Issue by aaroncaito** [Bash-it/bash-it#574]
I might be doing this wrong but I need to add additional stuff to path and my brew is in the boxen default path so the brew completion entry point is too early.

Anyhow in order to get stuff to load in the proper order I had to add this to 
$HOME/.bash_it/completion/custom.completion.path

```
export PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH=~/bin:/usr/local/bin:/usr/local/sbin:$PATH
# Boxen stuff
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
# Make brew happy
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

Attempting to add my local bin:/usr/local\* stuff in bash_it/custom loaded too late and caused issues.
Also had to redefine PATH on the first line each run otherwise performing `reload` just kept making my PATH grow.  Should there be somewhere that resets PATH? Should I manage PATH outside of bash_it ?

**Comment by nwinkler** [comment]
Here's a couple of things you could try:

* Instead of using a `custom` file to set your PATH, you could define it in your `~/.bash_profile`, before the line `source $BASH_IT/bash_it.sh`. This will make sure that your PATH is defined before Bash-it is loaded. The loading order is `aliases`, `completions`, `plugins`, `custom` - by putting your definition before that, you might hit the right spot.
* Instead of setting the PATH, you could use the `pathmunge` function. Depending on your OS, it might already be defined - if not, it's defined in https://github.com/Bash-it/bash-it/blob/94ffef8cf70cbb47d7651eaff70a673a33962ba7/lib/helpers.bash#L365. So instead of `EXPORT PATH=...`, you would use `pathmunge ~/bin`, which will avoid duplicates in the PATH.

Hope that helps...

**Comment by aaroncaito** [comment]
@nwinkler Great I think one of those will work just fine for my usage. Perhaps it should be mentioned in the docs?

**Comment by nwinkler** [comment]
Good to hear! Feel free to provide a PR for updating the documentation :smile:

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
