### ISSUE TITLE
How to submit a BASH_IT plugin?

### ISSUE THREAD

**Issue by marvindanig** [Bash-it/bash-it#577]
I'm currently writing a bash plugin for book writers and thought it would be worthwhile to share it with BASH_IT community.  It does a few simple things such as setting up a book project, adding pages, removing pages,  re-serializing directory, setting up repository etc. 

Should I just submit a PR or there is something else I that should do/read/evaluate with before submitting? 

Thanks!

**Comment by nwinkler** [comment]
Great - looking forward to your contribution!

Take a look at the other plugins, try to stick to the general format and naming conventions used in the other files, e.g. using dashes for function names instead of underscores (we're not consistent, but new submissions should try to stick to dashes).

There are also some meta tags like _group_ or _about_, please use them for describing your plugin and its functions.

Ideally your PR is rebased against the current _master_ and squashed into a single commit.

Once you have submitted, we'll review the PR and then provide comments.
