### ISSUE TITLE
Aliases depend on other parts of the project

### ISSUE THREAD

**Issue by PaulDapolito** [Bash-it/bash-it#704]
I really like Bash-it because it offers such an extensive set of resources for using and customizing Bash. I was disappointed to learn, however, that the aliases in `bash-it/aliases/available/` are dependent on other parts of the project.

For instance, I cannot simply `source bash-it/aliases/available/tmux.aliases.bash` without having previously installed the parts of Bash-it that include the `cite` and `about-alias` commands. This is disappointing because I do not want to execute the `install.sh` script from the script that sets up my shell environment. I do not find it appropriate to do so, as I have not closely examined every line of `install.sh`, and I do not need all of the functionality of Bash-it. I do not mean to say, in any way, that any contributors have had malicious intent in developing this script or that the script is otherwise shoddy. I simply do not need or desire all of Bash-it's functionality.

I was wondering what the project maintainers would think about slimming-down the aliases files provided by Bash-it such that they are no longer dependent on the `cite` and `about-alias` commands.

Thank you for your consideration.

**Comment by nwinkler** [comment]
The `cite` and `about-alias` functions have been added for providing meta information concerning the aliases, similar to what is being done with the plugins and completions. Running the `bash-it` command will show you some information about the aliases, e.g. `bash-it show aliases`. The displayed information is based on the content of the `about-alias` function.

It's perfectly OK if you do not want to run the `install.sh` script due to concern about its contents, but then I find it a bit strange that you're complaining about not being able to run some of the functionality. Similar to other software: If you don't install it, it won't run.

BTW: You don't need the install script. All it does is setting the `BASH_IT` environment variable and sourcing the main `bash-it.sh` script from your shell profile. You can add these two steps manually without running the installer and everything will work just fine.

Some other options that you might want to consider:

* Fork Bash-it and remove the `cite` and `about-alias` references.
* Move the alias files that you're interested in to a folder of your choice and source them from there after removing the references to the mentioned functions. 
* Move all of the alias definitions to your user's shell profile.

**Comment by PaulDapolito** [comment]
Thanks for your response, @nwinkler. I really appreciate your insight and the potential solutions you laid out for me. One other potential solution I thought of was to simply delete the first two lines of every aliases file in the script that sets up my shell environment.

One concern I have here is that, based on what you said, there is an inconsistency between the aliases files and the completions files, such that the completions do not depend on any other parts of the project and can be used as is (e.g. without running `install.sh`). I feel that Bash-it would be a stronger tool if the aliases files were able to be used independently of the rest of the project.

**Comment by PaulDapolito** [comment]
Hey @nwinkler,

What are your thoughts on simply guarding calls

**Comment by nwinkler** [comment]
How about defining noop-functions for `cite` and `about-alias` in your shell config, so that when you load the files, the functions are there, but don't do anything?

```
function cite() {
}

function about-alias() {
}
```

Wouldn't that fix your problem? And it's less invasive than adding a guard in each alias file...

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
