### ISSUE TITLE
`todo` folder messes up interactive installation

### ISSUE THREAD

**Issue by ayursha** [Bash-it/bash-it#710]
`bash-it/plugins/available` contains `todo` folder, whereas the installation code is not designed to have anything there which doesn't end in `.plugin.bash`. This messes up the installation with `--interactive` flag because `todo` folder is being `ls`ed inappropriately when gathering available plugin names. Its contents participates in user prompting as it it were plugins and the user is prompted if they want to install `todo plugins` 4 times which makes no sense and may lead to creating meaningless aliases.

**Comment by nwinkler** [comment]
Good point. In my own fork, I have deleted the `todo` folder and am using the official todo.txt installation instead.

Since there's no way to know who's using what, deleting an existing plugin is problematic...

@edubxb @tswicegood - How do we want to handle this? Delete the `todo` folder in the plugin directory, or change the installer to ignore it?

**Comment by edubxb** [comment]
As done with other plugins, I think that the best option is to delete the todo folder and use the official todo.txt installation, and use the plugin to load it.

**Comment by nwinkler** [comment]
That's what I've done in my fork - I'll create a PR for that...

**Comment by nwinkler** [comment]
Closed in #711
