### ISSUE TITLE
themes/powerline-multiline uses `command_exists` before base.plugin.bash loaded

### ISSUE THREAD

**Issue by jokeyrhyme** [Bash-it/bash-it#729]
When I use the powerline-multiline theme, I get "command_exists: command not found".

I think it's because the base.plugin.bash plugin is not yet loaded.

I have tried adding `bash-it enable base.plugin.bash` to my .bashrc, but themes are always loaded first, so this does not solve the problem.

Perhaps the base plugin should always be loaded internally? Or perhaps themes / plugins that depend on it should always explicitly load it themselves as a dependency?

**Comment by jokeyrhyme** [comment]
Here is where the theme calls `command_exists`:
- https://github.com/Bash-it/bash-it/blob/d25835fbb90fd5ea86bc808ca0b10a3a60b3a8c5/themes/powerline-multiline/powerline-multiline.theme.bash#L89

**Comment by jokeyrhyme** [comment]
I've also noticed that the battery plugin also uses it:
- https://github.com/Bash-it/bash-it/blob/d25835fbb90fd5ea86bc808ca0b10a3a60b3a8c5/plugins/available/battery.plugin.bash#L5

**Comment by nwinkler** [comment]
Yes, that's right - Bash-it does not have any kind of dependency management for plugins/themes or the like.

There are two issues here, that need to be looked at separately:

## Plugin dependencies
The `battery` plugin uses `command_exists`, which is defined in the `base` plugin - this is just one example, there are probably more than that. In this case, it works if you enable both `base` and `battery`, since they are loaded in alphabetical order, which means that `command_exists` will be available once `battery` is loaded. 

There is no check for this, however. Making this more robust would require to introduce dependencies and creating a dependency tree upon loading. We're not going to tackle that at the moment...

## Themes using functionality from plugins
This is indeed an issue. Enabling the `base` plugin (which you only need to do once by running `bash-it enable plugin base` - don't do this from your `~/.bashrc`) will not help, since the loading order looks like this (in `bash_it.sh`): 

1. `lib/composure.bash`
1. Base Theme
1. `lib/*.bash`, which loads the `BASH_IT_THEME` from `appearance.sh`
1. Aliases
1. Completions
1. Plugins
1. `custom/*.bash`

You can clearly see that plugins are loaded after the theme. Two ways to fix this:

1. Change the order, so that the theme is loaded last. This would allow themes to use any plugin functionality, with the above caveat that there's no dependency management.
1. Move the `command_exists` function into either the `lib/appearance.sh` or into the `themes/base.theme.bash` file. Potentially use an `if` safeguard around it to avoid defining it again.

@tswicegood @edubxb - what do you think?

**Comment by jokeyrhyme** [comment]
Pretending for a minute that we have a real dependency tree, themes would always be leaves. It doesn't make sense for plugins to depend on themes, so it could make sense to always load enabled plugins prior to loading the selected theme.

**Comment by nwinkler** [comment]
I agree - now someone needs to make that change and verify that it doesn't have any side effects... PRs welcome...
