### ISSUE TITLE
Got some errors when run  ./install.sh

### ISSUE THREAD

**Issue by crazy-canux** [Bash-it/bash-it#746]
Enabling sane defaults
ln: failed to create symbolic link ‘/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/completion/enabled/bash-it.completion.bash’: Read-only file system
ln: failed to create symbolic link ‘/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/completion/enabled/system.completion.bash’: Read-only file system
ln: failed to create symbolic link ‘/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/plugins/enabled/base.plugin.bash’: Read-only file system
ln: failed to create symbolic link ‘/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/plugins/enabled/alias-completion.plugin.bash’: Read-only file system
ln: failed to create symbolic link ‘/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/aliases/enabled/general.aliases.bash’: Read-only file system

**Comment by nwinkler** [comment]
What happens if you run something like

```bash
bash-it enable plugin base
```

or even simpler

```bash
touch /home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/completion/enabled/foo.txt
```

Does either one of these work? If not, some questions:

* Did you install Bash-it in `/home/chengca/Share/myCode/xDevOps/etc/shell/bash.d/bash-it/`?
* If not, where did you install it?
* If you installed it there, is the file system writable? I imagine it must be, since you somehow were able to clone Bash-it to that location.
* Did you call the `install.sh` script from its own directory, or from some other location?

**Comment by crazy-canux** [comment]
I know what happen,
I put the repo on the share folder between virualbox and windows 7.
That's why I can not link.
So I moved the repo to other place on my ubuntu.
