### ISSUE TITLE
Advise for ~/.bashrc

### ISSUE THREAD

**Issue by crazy-canux** [Bash-it/bash-it#748]
Can we comment everything except 

"export BASH_IT="/home/chengca/.bash.d/bash-it"
"export BASH_IT_THEME='bobby"
"source $BASH_IT/bash_it.sh"

In ~/.bashrc after install?

Because I think we should let the user decide which function to use except those necessary?

**Comment by crazy-canux** [comment]
Just like oh-my-zsh.

**Comment by crazy-canux** [comment]
And, can I random the theme?
Every time open the shell you got different theme?

**Comment by nwinkler** [comment]
Regarding the `~/.bashrc`: Sure, you can remove anything you like from the file once it has been generated by the install script - only keep the three lines above, as they are required for Bash-it to work.

Other than that, feel free to change the file as you like. Some of the options are in there for historical reasons (since nobody cared to remove them) - I find they don't hurt.

**Comment by nwinkler** [comment]
Regarding the random theme: There's a `random` theme in #301, but the PR was never merged since it contained lots of other changes that shouldn't have been in the PR.

Feel free to take just the `random` theme from this PR and provide it as a new clean PR...

**Comment by crazy-canux** [comment]
Ok, I see.
Thanks for your comment.
