### ISSUE TITLE
[discussion] custom scripts, aliases and functions directory like custom themes

### ISSUE THREAD

**Issue by MunifTanjim** [Bash-it/bash-it#802]
Currently for custom scripts, aliases and plugins, only one file each is allowed which will be ignored by git : `aliases/custom.aliases.bash`, `completion/custom.completion.bash` and `plugins/custom.plugins.bash`. And they are automatically sourced by bash-it.

That works. But sometimes user may want to have several of those custom scripts (which will not be included to git repo) and the ability to enable/disable them via regular bash-it commands (rather than automatically source them) would be really great.

So, I have a suggestion. Bash-it will have the following structure for custom scripts:
```
bash-it
-- custom
---- aliases
------ exampleA1.aliases.bash
------ exampleA2.aliases.bash
------ (...)
---- completion
------ exampleC1.completion.bash
------ (...)
---- plugins
------ exampleP1.plugin.bash
------ (...)
```

And bash-it regular enable/disable commands will be able to work with these custom scripts. For example:
`bash-it enable completion exampleC1` command will create a link for `bash-it/custom/completion/exampleC1.completion.bash` in `bash-it/completion/enabled/`.

If that adds extra complexity (because 2 directory will have to be searched for TAB completion of those commands), we can just add another option `custom` to enable/disable command, so that: `bash-it enable custom completion <name>` will only enable custom completion scripts.

Thoughts?

**Comment by nwinkler** [comment]
Good point. A couple of thoughts:

* In addition to the `custom.completion.bash` (etc.) file(s), there is the `custom` directory, which is loaded after all of the other files. Anything ending in `.bash` in `custom` is loaded, which means that you can have several files there. There's no separation between aliases, completions or plugins, and you can't enable/disable them using a command, but it gives the user some freedom to load files that are not part of the Git repo. I use this for setting environment variables that differ between home/work for example.
* Do you really see a big use case in this? Are people creating their own aliases, plugins and completions that they don't want to be part of the Git repo? I always assumed that if you spent time with creating something like that, you'd want to store it somewhere so that it survives a crash. I don't know, maybe there is a use case for this...

Adding what you suggested shouldn't be too much work, like you said, it's adding a second directory to the enable/disable/show commands. We'll have to think about name conflicts, though, e.g. in case there's a plugin with the same name in both `custom` and `available`- which one takes precedence (`custom`, I guess)?

I think it would be a good addition, but I'd like to understand first whether it's a real use case. Do you have examples of what you would put there?

Let me know what you think...

**Comment by MunifTanjim** [comment]
I didn't knew that every `.bash` files in `custom` directory were loaded. That satisfies my needs.

So now, I can't really think of any real use case of the things I previously mentioned. :slightly_smiling_face:

**Comment by nwinkler** [comment]
Thanks - closing this now...

**Comment by rahul0705** [comment]
I kinda want to open this back up (necro) would it be possible to add this functionality or mirror something like [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization)?

**Comment by nwinkler** [comment]
@rahul0705 Sure - we can look into this. If you have a suggestion on how to implement something like oh-my-zsh's plugin mechanism, let's hear it...
