### ISSUE TITLE
Revert Powerline Theme colors

### ISSUE THREAD

**Issue by Rockstar04** [Bash-it/bash-it#835]
It looks like the changes made in #815 modified the colors used for git repo display. In my terminal this displays blue text on a blue background (exact same colors). The changes in #815 seem good for deduplication of code, but the changes to the theme appearance should be reverted in my opinion, or at the very least changed so the text can be read.

I copied the theme that was in place in commit [af96da5](https://github.com/Bash-it/bash-it/tree/af96da5d11bccb16923694fd68cda557200882db) and the theme colors are what I expect.

**Comment by nwinkler** [comment]
@edubxb - want to take a look?

Thanks for reporting this issue, @Rockstar04!

**Comment by Rockstar04** [comment]
Here is a screenshot with the current and old powerline themes. I start out with the "Legacy powerline-plain" then switch to the current version.

![screenshot_2016-11-14_10-23-03](https://cloud.githubusercontent.com/assets/641721/20272761/8abf4b9c-aa54-11e6-8b07-6e95724881ce.png)

**Comment by edubxb** [comment]
I will fix tonight, sorry.

Also, I will add the possibility to overwrite the theme colors.

**Comment by edubxb** [comment]
@Rockstar04 can you change the theme to the current powerline-plain and open a fresh terminal? how the git segment looks?

The changes introduced in powerline themes updates the background color according to the git repository status, the foreground is the default of the terminal. IMHO this improves readbility.

See how it looks in mi laptop:
![screenshot powerline-plain](https://cloud.githubusercontent.com/assets/1192339/20280174/a7ece894-aaab-11e6-8930-56f64e6ecd83.png)

**Comment by Rockstar04** [comment]
Opening a new terminal did change the text colors, but its not the same as your terminal, and defiantly not the same as what the theme was. If powerline is supposed to be like your screen cap above, I'll keep using the legacy version.

![screenshot_2016-11-14_14-11-11](https://cloud.githubusercontent.com/assets/641721/20281120/c7d55632-aa74-11e6-8cee-50a7bbeff8f8.png)

**Comment by edubxb** [comment]
I my screenshot the username has been removed (by config), in your screenshot, the username background is "orange" (the default is blue) because you have the sudo credentials cached (that can be reset with `sudo -k`), I guess...

I'm thinking into add more flexibility to the powerline themes:

- First, allowing changing the colors, as I said in my previous comment
- Second, an "alternative display mode", the default mode will be the current (dynamic background, static foreground), and the "alternative", the previous one (static background, dynamic foreground). This may be chosen individually to every "segment".

What do you think about my proposal?

I will try to do it this week...

**Comment by Rockstar04** [comment]
If its all intended behavior don't feel like you need to change anything. I'm quite happy with my "legacy" version of the theme. It was just unexpected that a theme would change this drastically and keep the same name.

I'm fine with this being closed, marked up to quarks with my install of Xubuntu.

**Comment by edubxb** [comment]
You're right, I changed the theme behavior when unifying the powerline themes, I'm so sorry...

But I will try to make everyone happy :yum: 

Reverting the powerline-plain theme to the legacy "style" can make the base code of powerline themes a bit more complex, so I prefer to add more complexity adding flexibility, to allow more options to users.

I will made the changes I suggested and you can use the theme as before.

So I will keep this issue open until the changes are made, no worry with that.

**Comment by Rockstar04** [comment]
Sounds good. Thanks @edubxb. I'll be watching for the update.

**Comment by mhite** [comment]
I hit upon the same orange prompt issue and unfortunately `sudo -k` never made it go away. I'm pretty sure I get a perpetual orange prompt because of the following sudo policy:

```
# Ops group is allowed ALL
%ops ALL=(ALL) NOPASSWD: ALL
```

As a quick hack to disable this orange prompt behavior, I placed this on the end of `.bashrc` after `bash_it.sh` is sourced.

```
# Load Bash It
source $BASH_IT/bash_it.sh
export THEME_CHECK_SUDO=false
```

I think, in general, that the current practice of changing the prompt when "sudo right to elevate without credentials" is available is a bit undesirable in certain cases like the aforementioned.

Perhaps the best path forward is to  create a POWERLINE_THEME_CHECK_SUDO option which overrides the default THEME_CHECK_SUDO in the theme? This would at least allow the user to disable this sudo check without having to order it below the `source $BASH_IT/bash_it.sh` command in .bashrc.

What do you think?

**Comment by nwinkler** [comment]
Sounds like a good idea to me - you want to take a stab at implementing this?

**Comment by glats** [comment]
Any news about this?

**Comment by nwinkler** [comment]
Seems like nobody has picked this up so far. One of you interested in contributing a PR for this, @glats or @mp4096?
