### ISSUE TITLE
Where to config PS1?

### ISSUE THREAD

**Issue by arimourao** [Bash-it/bash-it#892]
Hey there,

I'm not much knowledgeable in bash, but I have configured a nice PS1 using an editor some time ago. In a first look I thought PS1 was in one of the themes, but I couldn't find there. Where should I add my custom PS1?

**Comment by nwinkler** [comment]
What you probably want to do is create your own theme. Please take a look at the themes in the `themes` folder. The PS1 is created in the theme, e.g. here: https://github.com/Bash-it/bash-it/blob/master/themes/bobby/bobby.theme.bash#L26

**Comment by dayne** [comment]
I was trying to figure out how to customize my PS1 to add in a feature I need.. found the themes and wanted to dive into this.  However I can't seem to get *any* theme to take hold - let alone a custom one.

```
 2017-03-23 23:13:17 ⌚  x100e in ~
○ → echo $BASH_IT_THEME
bobby

 2017-03-23 23:13:26 ⌚  x100e in ~
○ → export BASH_IT_THEME='duru'

 2017-03-23 23:13:50 ⌚  x100e in ~
○ → reload

 2017-03-23 23:13:51 ⌚  x100e in ~
○ → 
```

Any ideas what I am doing wrong in trying to get a new theme to take hold?  

I even tried directly setting `PS1='$'` to no effect.

Everything I try todo to modify the prompt or theme has no effect.

**Comment by nwinkler** [comment]
The theme is set in your `~/.bashrc` (or `~/.bash_profile`, depending on the OS). When you call `reload`, the `BASH_IT_THEME` variable is loaded from that file, overwriting what you have exported previously.

If you want to try a different theme, you need to edit the `~/.bashrc` file where the `BASH_IT_THEME` variable is exported, and then call `reload`.

The `reload` alias simply sources your shell configuration file again, that's why you're not seeing your changes.

**Comment by dayne** [comment]
Ahh. So an on the fly change was a no go.  Thanks.

I ended up figuring that out but my initial expectation of on the fly changing that and using reload was off base. 

Thanks.

Tossed in a pull request to allow for direct file path linking to a theme file so I can track my theme outside of the bash-it git repo.

Enjoying  bash-it.  Thanks!

**Comment by nwinkler** [comment]
Thanks for the PR! I'm closing this one now...
