### ISSUE TITLE
Dynamically setting variables based on PWD filesystem type

### ISSUE THREAD

**Issue by cleeland** [Bash-it/bash-it#906]
I frequently have to work on SCM repositories that are on high-latency links (remote filesystems).  Doing things like "git status" is a painfully long operation.  I also frequently work on SCM repositories that are locally hosted.

I would like to device a bash-it "something"--plugin? theme adjunct? hook?--that could set `SCM_*` variables in my shell based on the fstype of the pwd.

1. If there is already something like this, then point me towards it.
2. If not 1, then I would appreciate guidance as to which framework facility this would best use (plugin? theme?)
3. if this is not the correct forum in which to ask questions such as this, please advise on where (I'll also submit a pull request to the readme that includes the correct forum for questions).

**Comment by nwinkler** [comment]
You're absolutely at the right place here - feel free to ask questions!

Since the `git status` calls are made as part of a theme implementation, that's where you would implement something like this.

I recommend to take a look at the `base.theme.bash` file, since this is where the whole SCM check is made. You could add your `fstype` check in there, as an `if` statement around the whole `scm` functionality.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
