### ISSUE TITLE
how to fully remove bash-it (get back to the normal before)

### ISSUE THREAD

**Issue by ghost** [Bash-it/bash-it#912]

**Comment by arimourao** [comment]
Try running the uninstall script in ~/.bash-it (or wherever you cloned your repo). It should restore your original .bashrc file. Then you can delete your bash-it folder.

**Comment by nwinkler** [comment]
Don't forget to close your terminal window after you ran the `uninstall.sh` script. Open a new window/session, and you should be back to normal.

Sorry to see you go, @rafiksemaan - what didn't you like about Bash-it? Any feedback that would help us improve Bash-it?

**Comment by ppcuban** [comment]
I am uninstalling it because I am stuck with one theme. It wouldn't reload the 'iterate' theme. Also, I see way too many issues here regarding other aspects of the terminal being 'broken' after installing bash-it. 

Landed here with a lot of dreams... got myself into a nightmare :(

**Comment by nwinkler** [comment]
Sorry to hear that - that's certainly not the user experience we want to see for Bash-it's users.

Can you be more specific with regards to your issues?
* What do you mean when you say that it would not reload the `iterate` theme?
* Why are you stuck with one theme?
* Where do you see these many issues with things being broken after installing Bash-it?

Would be great if you could provide some more info on this so we can look into providing a better experience.

In general, many issues happen because people select to enable all plugins during the installation - this is not a good idea (we might want to remove that option from the installer). I suggest to enable the default settings and then go from there.

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
