### ISSUE TITLE
Prompt slow after every command (macOS Sierra)

### ISSUE THREAD

**Issue by edfungus** [Bash-it/bash-it#914]
After I updated to macOS Sierra, it take about 3-5 seconds for the next prompt to come up after I type a command. If I do not load bash_it, my terminal is normal speed. This affected both terminal and iTerm. The slowness makes the terminal really frustrating to use 

Does anyone have some light to shed on this problem?

**Comment by edfungus** [comment]
I was using the bobby theme and looks like `$(ruby_version_prompt)` and `$(scm_prompt_info)` caused the slow down

**Comment by nwinkler** [comment]
Are you in a Git repo when this happens, or is the prompt slow for all directories?

**Comment by edfungus** [comment]
It happens throughout all folders but was especially bad in a git repo folder

**Comment by trinitronx** [comment]
I am seeing the same exact problem on my work laptop.  It has become so frustratingly a waste of time that usually I turn off my `~/.bashrc` entirely to get anything done.  With time pressures from Sprint / Iteration tasks, this is a huge "death by papercut" issue that is causing me daily problems.

Just like @edfungus, I'm seeing slowdowns in all directories but especially bad in git repo folders.  Additionally, I am using `ruby_version_prompt`, and it seems to be decently fast for me on my work laptop running Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51 .

This weekend (the only time I am allowed to work on this), I have finally tracked down the issue to the `bobby.theme` calls to `scm_prompt_char_info` and `scm_prompt_info` as well.

 - On my work laptop, I'm running:
   - Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51 (**SLOW**)
   - I have tested:

       | `PS1` | Speed | Time Profiling |
       |-------|-------|----------------|
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_prompt_char_info) ${green}→${reset_color} "` | **SLOW** |  ~ 2-4 seconds |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW** | ~ 2-4 seconds |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **DECENT** | 365.5 ms average |

 - On my home laptop, I'm running:
   - Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834 (**FAST**)
   - I have tested:

       | `PS1` | Speed | Time Profiling |
       |-------|-------|----------------|
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **FAST** | 303.8 ms average |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **FAST** | 67.6 ms average |


As you can see from the results, turning these off and simply using `scm_char` appears to be better for both tested versions of `bash-it`.  I also tested setting `export SCM_GIT_SHOW_MINIMAL_INFO=true` when using `scm_prompt_info` OR `scm_prompt_char_info` seems to mildly help, but is still slow.  The implementation hasn't changed too much from Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834 to Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51 , but I notice a couple things at first glance:

1. The old version on my home laptop (Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834) does **NOT** have the new functions: `scm_prompt_char_info`, and `scm_prompt_info_common`
2. The new version on my work laptop (Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51) has these two functions added, `scm_prompt_info_common` is called by **both** `scm_prompt_info` and `scm_prompt_info_common`.  Finally, the function `scm_char` has changed it's output from `$SCM_CHAR` to `${SCM_THEME_CHAR_PREFIX}${SCM_CHAR}${SCM_THEME_CHAR_SUFFIX}`

So, based on this information I deduce that the new function call to `scm_prompt_info_common` has incurred a call stack penalty from calling a new function where none was made before.  When speed matters, such as in our example of printing a `PS1` line every time the user hits "`enter`", this penalty becomes noticeable.  In the case of simply using `scm_char`, the extra data printed by `echo` does seem to somehow take longer noticeably in the order of milliseconds.  Time between hitting enter in this case is generally fast or decent enough to ignore speed.  However, I still am not sure that the change for calling `scm_prompt_info_common` should be in the order of seconds.

**Comment by trinitronx** [comment]
The file difference between the `base.theme.bash` is this:

```
--- /Users/jcuzella/.bash_it/themes/base.theme.bash	2017-02-05 02:38:02.000000000 -0700
+++ /tmp/work-laptop/.bash_it/themes/base.theme.bash	2017-03-29 18:18:11.000000000 -0600
@@ -20,6 +20,8 @@
 SCM_THEME_BRANCH_GONE_PREFIX=' ⇢ '
 SCM_THEME_CURRENT_USER_PREFFIX=' ☺︎ '
 SCM_THEME_CURRENT_USER_SUFFIX=''
+SCM_THEME_CHAR_PREFIX=''
+SCM_THEME_CHAR_SUFFIX=''
 
 THEME_BATTERY_PERCENTAGE_CHECK=${THEME_BATTERY_PERCENTAGE_CHECK:=true}
 
@@ -92,6 +94,16 @@
 function scm_prompt_info {
   scm
   scm_prompt_char
+  scm_prompt_info_common
+}
+
+function scm_prompt_char_info {
+  scm_prompt_char
+  echo -ne "${SCM_THEME_CHAR_PREFIX}${SCM_CHAR}${SCM_THEME_CHAR_SUFFIX}"
+  scm_prompt_info_common
+}
+
+function scm_prompt_info_common {
   SCM_DIRTY=0
   SCM_STATE=''
 
@@ -429,7 +441,7 @@
 
 function scm_char {
   scm_prompt_char
-  echo -e "$SCM_CHAR"
+  echo -e "${SCM_THEME_CHAR_PREFIX}${SCM_CHAR}${SCM_THEME_CHAR_SUFFIX}"
 }
 
 function prompt_char {

```

There are probably other differences that may impact these times in `ruby_version_prompt` as well.  However, I did not look further into this, as just switching to using `scm_char` alone on my work laptop seems to have made a significant difference in the order from seconds to milliseconds.

**Comment by nwinkler** [comment]
Thanks for the great analysis! Just to make sure that this is not related to the individual laptop you're using:

* Are you using the same Git repo to test this on both laptops? Are you hitting Enter in the same Git repo clone on each of the laptops? The size of the repo might make a huge difference.
* When you switch to the older (and faster on your home laptop) Git revision on your work laptop, does it run faster there as well?

Let me know what you find there, and then we can look into getting it changed.

**Comment by chandradeepak** [comment]
@nwinkler , i also started seeing slowness in my prompt . Is there a work around right now to fix this ?

**Comment by r2ro** [comment]
Same.  Upgraded to Sierra and now my prompt is incredibly slow.  About to uninstall it unless there is a workaround/fix?

**Comment by chandradeepak** [comment]
@nwinkler , @edfungus    I found the reason for my slowness . 

These were the two that were causing the slowness in my terminal 

in the base.themes.bash
` local stash_count="$(git stash list 2> /dev/null | wc -l | tr -d ' ')"
  [[ "${stash_count}" -gt 0 ]] && SCM_BRANCH+=" {${stash_count}}"`


there is code which gets the stash count and my particular repo had 24 stashed version. 
This was causing a 3 second  delay .  I commented that since i don't care about how many stashed items are there .  

Also another cause of the issue is in the bobby/bobby.theme.bash
` PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_prompt_char_info) ${green}→${reset_color} "

replaced that with 

PS1="\n$(battery_char) $(__bobby_clock)${yellow} ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_prompt_char_info) ${green}→${reset_color} "
`

The $(ruby_version_prompt) is taking 1 second to execute . so taking that out decrease my 1 second delay. 


So over all my performance right now is 

_**real	0m0.018s**_
user	0m0.005s
sys	0m0.010s

from 

_**real	0m4.108s**_
user	0m3.912s
sys	0m2.110s

so overall my performance increased greatly and i am happy with bash_it again . 

Lesson learnt
1) it is not always other repo problem 
2)git stash list is a costly command especially if u have lot of stashed items 
3)ruby version prompt is slow
4) SCM_CHECK=false  need not be solution in my case since that takes away all the good stuff bash_it provides .
Thanks to @trinitronx  for his detailed explanation .

**Comment by andycoates** [comment]
`git stash list` is what's causing the "lag" for me, enough to be noticeable and annoying.  I commented out the stash calculation and its much much better (and something I can live without). 

It is odd it only affects my OSX prompts though.  It's 0.08s or so in OSX (tried git 2.11.0 from Apple, and 2.13.0 from homebrew) and about 0.02s in Linux (Ubuntu 14.04's git 1.9.1 is about 0.015s and 2.13.0 is 0.02s)

**Comment by nwinkler** [comment]
Good analysis! Anybody willing to add a config variable check (similar to `SCM_CHECK`) around the `git stash` command to enable/disable this on demand?

**Comment by trinitronx** [comment]
@nwinkler:  Good questions!  To answer these questions you asked earlier:

 - **Q:** Are you using the same Git repo to test this on both laptops? Are you hitting Enter in the same Git repo clone on each of the laptops? The size of the repo might make a huge difference.
   - **A:** Yes, the same identical repo checkout was used on both laptops, also using the same exact path to the checked out repo.  Note that I do have a [small recursive function](https://gist.github.com/trinitronx/5979265) that does affect time between prompt _display_ events.  The testing methodology of using a bash `$()` subshell to run the `date` command to measure the timestamp samples happens during the time just before and just at the end of the `PS1` bash string `eval` step being run.  The thinking was: Because my shell used this `git` alias (`alias git='__set_git_email_vars; __set_git_name_vars; hub'`), the time to execute `git` commands may be slightly higher than usual.  So my timing results may not match exactly a typical user, and I am using the `hub` gem also which affects the timing.  However, because I use this on both of my laptops, and I was careful to run the command from the same repo & path each time this data should be easy to compare between my laptops as "apples to apples", because the same code was running from the same directory path yielding the same average time padding.  All things being equal, the time differences between my data points should be isolated to the version of `~/.bash-it` and `base.theme.bash`.  I think perhaps since `bash-it` cannot guarantee that the SCM commands are not aliases for each user, it may make sense for these informational `PS1` "data query" type SCM commands to be run in [some way to prevent bash alias expansion][bash-alias-break].  Perhaps in `themes/base.theme.bash` wherever a command name is mentioned such as `SCM_GIT='git'`, instead it could be expanded to the full command path: `SCM_GIT="$(which git)"`.  This would always use the bare command, providing a bit of a speed increase to users with aliased commands.  The tradeoff is this will break things if the user expects to be able to hook these commands via an alias in order to perform some side-effect behavior in their prompt.  For my case,   Arguably using an alias as a hook is a bit of a hack rather than the user creating their own theme, or contributing to the `bash-it` code.  I'm sure also as @andycoates mentions, depending on the particular version of `git` being used (whichever is first in user's path).
 - **Q:** When you switch to the older (and faster on your home laptop) Git revision on your work laptop, does it run faster there as well?
   - **A:** This is also a good idea that I did not yet test.  Perhaps it is good just to double check that there isn't something else on this laptop that is causing the slowdowns.  This could take a moment, so I'll post in a separate comment with results.

[bash-alias-break]: https://stackoverflow.com/questions/6162903/why-do-backslashes-prevent-alias-expansion

**Comment by trinitronx** [comment]
So, I just tested this on my work laptop by doing: `cd ~/.bash_it/ && git checkout 40f26ce`.  Because this version does not have the new `scm_prompt_char_info` function, the `PS1` prompts from f3d229e return `-bash: scm_prompt_char_info: command not found`.  When I test the new ones (same ones as on my home laptop, I get the following results:

 - On work laptop, running:
   - Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834 (**FAST**)
   - I have tested:

       | `PS1` | Speed | Time Profiling |
       |-------|-------|----------------|
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW** | 3.853 seconds average |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **DECENT** | 531 ms average |

**Comment by trinitronx** [comment]
After analyzing the above results, it looks like there is still some difference between my home and work laptops which is causing the work laptop to be slower in the first test case, even with the same revision (Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834) checked out in `~/.bash_it`.  Luckily, I also use a [Chef cookbook for this `bash_it` custom plugin][lyraphase_workstation_bash_it_recipe], which places [this file][lyraphase_workstation_bash_it_custom_git_plugin] in `~/.bash_it/custom`.  It was run recently enough that the files are identical:

    # In my chef cookbook for this file:
    $ shasum -a 256  ~/src/pub/cookbooks/lyraphase_workstation/templates/default/bash_it/custom/git-custom_subdir_gitconfig.aliases.bash
    48a926c6c7d70edcb41bd4f78bde4f8b663f4889eb6fe89e5c27ec777edb5891  ~/src/pub/cookbooks/lyraphase_workstation/templates/default/bash_it/custom/git-custom_subdir_gitconfig.aliases.bash
    
    # On my work laptop
    $ shasum -a 256  ~/.bash_it/custom/git-custom_subdir_gitconfig.aliases.bash
    48a926c6c7d70edcb41bd4f78bde4f8b663f4889eb6fe89e5c27ec777edb5891  ~/.bash_it/custom/git-custom_subdir_gitconfig.aliases.bash

    # On my home laptop
    $ shasum -a 256 ~/.bash_it/custom/git-custom_subdir_gitconfig.aliases.bash
    48a926c6c7d70edcb41bd4f78bde4f8b663f4889eb6fe89e5c27ec777edb5891  ~/.bash_it/custom/git-custom_subdir_gitconfig.aliases.bash

So this can't be the issue.  Perhaps it's different versions of `hub` and `git`?

    # On work laptop
    $ ls -l $(which hub)
    lrwxr-xr-x  1 jcuzella  wheel  27 Sep 13  2016 /usr/local/bin/hub -> ../Cellar/hub/2.2.8/bin/hub
    $ file /usr/local/Cellar/hub/2.2.8/bin/hub
    /usr/local/Cellar/hub/2.2.8/bin/hub: Mach-O 64-bit executable x86_64
    $ hub version
    git version 2.10.0
    hub version 2.2.8
    $ ls -l $(which git)
    lrwxr-xr-x  1 jcuzella  wheel  28 Sep 13  2016 /usr/local/bin/git -> ../Cellar/git/2.10.0/bin/git
    
    # On home laptop
    $ ls -l $(which hub)
    lrwxr-xr-x  1 jcuzella  staff  27 Jun  8  2015 /usr/local/bin/hub -> ../Cellar/hub/2.2.1/bin/hub
    $ file /usr/local/Cellar/hub/2.2.1/bin/hub
    /usr/local/Cellar/hub/2.2.1/bin/hub: Mach-O 64-bit executable x86_64
    $ hub version
    git version 2.10.0
    hub version 2.2.1
    $ ls -l $(which git)
    lrwxr-xr-x  1 jcuzella  staff  28 Oct  3  2016 /usr/local/bin/git -> ../Cellar/git/2.10.0/bin/git

So this is with same version of `git` (`2.10.0` from Homebrew), but different versions of `hub` `2.2.8` vs. `2.2.1` (also both from Homebrew).

[lyraphase_workstation_bash_it_recipe]: https://github.com/trinitronx/lyraphase_workstation/blob/master/recipes/bash_it_custom_plugins.rb
[lyraphase_workstation_bash_it_custom_git_plugin]: https://github.com/trinitronx/lyraphase_workstation/blob/master/templates/default/bash_it/custom/git-custom_subdir_gitconfig.aliases.bash

**Comment by trinitronx** [comment]
After realizing that `hub` and my [custom `git` alias][custom-git-alias] may be partly to blame, I decided to do another test modifying the `base.theme.bash` using a couple alternative methods to bypass the `git` `alias`:


 - On work laptop, running:
   - Bash-it/bash-it@40f26ce40dad32e74eff7ccc3e5cda67fc054834 (**FAST**)
   - I have tested:

       | `PS1` | Speed | Time Profiling | Patch Applied |
       |-------|-------|----------------|---------------|
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW** | 2.045 seconds average (1.808 s faster than with `hub` + alias) | [Setting `SCM_GIT="$(which git)"`][bash_it_which_patch] |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **DECENT** | 534.3 ms average (3.3 ms slower than with `hub` + alias) | [Setting `SCM_GIT="$(which git)"`][bash_it_which_patch] |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW** | 2.058 seconds average ( 1.795 s faster than with `hub` + alias) | [Setting `SCM_GIT="command git"`][bash_it_command_patch] |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **DECENT**  | 536.3 ms average (5.3 ms slower than with `hub` + alias) | [Setting `SCM_GIT="command git"`][bash_it_command_patch] |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **DECENT** | 559.5 ms average ( 3.2935 s faster than with `hub` + alias) | [Setting `SCM_GIT='\git'`][bash_it_backslash_patch] |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "` | **DECENT** | 533.2 ms average (2.2 ms slower than with `hub` + alias) | [Setting `SCM_GIT='\git'`][bash_it_backslash_patch] |


## Analysis:

We have a couple differences between the previous test.  Generally the prompts with `scm_prompt_info` perform faster across the board with all 3 patches tested.  The prompts with just `scm_char` are a couple milliseconds slower, but this is probably negligible and with more data points I'm sure it would probably be statistically insignificant.

The fastest performing patch was with setting `SCM_GIT='\git'` and using `$SCM_GIT` in place of the bare `git` calls everywhere.  I'm sure if I tested on the home laptop with the older versions of `bash` and `bash-completion`, that this would most likely be faster there as well.

[custom-git-alias]: https://github.com/trinitronx/lyraphase_workstation/blob/master/templates/default/bash_it/custom/git-custom_subdir_gitconfig.aliases.bash
[bash_it_which_patch]: https://gist.github.com/0728d0f8049d402b7d9b6aa7001c2b9e
[bash_it_command_patch]: https://gist.github.com/9a8e29475a119bb70bda86c55ee34f79
[bash_it_backslash_patch]: https://gist.github.com/2487156dd92367d367d93597ba37fdba

**Comment by trinitronx** [comment]
Ok, so maybe I spoke too soon without realizing that the backslash tests actually are not returning the prompt info for a git repo.  It looks like many calls to `git` are using `2>/dev/null` to [redirect stderr](https://github.com/Bash-it/bash-it/blob/master/themes/base.theme.bash#L153).

Hence, in my tests I failed to notice the missing prompt info and error `-bash: \git: command not found`.  It seems that many of the [alternate methods for disabling an alias](https://stackoverflow.com/questions/6162903/why-do-backslashes-prevent-alias-expansion) were not effective when used as a variable to be evaluated by the `$()` subshell bash syntax.  The single ``` and double `"` quotes, as well as backslash `\` method do not appear to work in this context.

So the reason for those being faster is that they are not actually forking off a `git` command, but silently throwing the `command not found` error to `/dev/null`.  Unfortunately that means that this solution doesn't work as the patch is coded.  Maybe some more experimentation is needed here, but at least `command git` seems to work.

**Comment by trinitronx** [comment]
Based on previous findings, I decided to try [making a couple changes][bash_it_optimize_1]:

1. Added new option `SCM_GIT_SHOW_STASH_INFO` for turning on or off the `git stash` info & call
2. Set `SCM_GIT='command git'`; Replace all calls to `git` with `$SCM_GIT`
3. Create new variable `SCM_GIT_HIDE_STATUS` with output from call to `git config --get bash-it.hide-status`.  Note that this caches this `git config` call's result until the next shell is opened.  Should make things faster due to less `git` calls, but config option will not take effect until next time `~/.bash_it` is loaded.

Using this patch, I tried the 2 `PS1` prompts I've been testing.  This time, I played with some of the `SCM_GIT_*` variable settings to see what is slowing things down.  I also decided to use the later `bash-it` revision: Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51

Below is a sorted list from **SLOWEST** to **FASTEST** `PS1`:

 - On work laptop, running:
   - Bash-it/bash-it@f3d229e5cb89424e0a2465117cd6081e91d6bf51
   - I have tested:

       | `PS1`                                                                                                                                                                                         | Speed        | Time Profiling           | Patch Applied                                            | bash-it.hide-status | SCM_GIT_SHOW_STASH_INFO     | SCM_GIT_SHOW_CURRENT_USER | SCM_GIT_SHOW_DETAILS | SCM_GIT_SHOW_REMOTE_INFO | SCM_GIT_IGNORE_UNTRACKED | SCM_GIT_SHOW_MINIMAL_INFO |
       |-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|--------------------------|----------------------------------------------------------|---------------------|-----------------------------|---------------------------|----------------------|--------------------------|--------------------------|---------------------------|
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW**     | 2.432 seconds average    | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | true                        | true                      | true                 | true                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW**     | 2.158 seconds average    | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | true                        | false                     | true                 | auto                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW-ISH** | 1.052 seconds average    | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | false                       | false                     | true                 | auto                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **DECENT**   | 791.7 ms average         | [Test Optimization Patch #1][bash_it_optimize_1]         | 1                   | false                       | false                     | true                 | auto                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "` | **SLOW**     | 759.6 ms average         | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | false                       | false                     | true                 | auto                     | false                    | true                      |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "`                            | **DECENT**   | 534.5 ms average         | [Test Optimization Patch #1][bash_it_optimize_1]         | 1                   | false                       | false                     | true                 | auto                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "`                            | **DECENT**   | 531.9 ms average         | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | false                       | false                     | true                 | auto                     | false                    | false                     |
       | `PS1="\n$(battery_char) $(__bobby_clock)${yellow}$(ruby_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}→${reset_color} "`                            | **DECENT**   | 530.9 ms average         | [Test Optimization Patch #1][bash_it_optimize_1]         | 0                   | true                        | false                     | true                 | auto                     | false                    | false                     |





[bash_it_optimize_1]: https://gist.github.com/2f10d71020c27a76bd1d50c24bfcdb20

**Comment by nwinkler** [comment]
Wow - great analysis! Thanks for spending the time to look into this with so much detail!

**Comment by trinitronx** [comment]
@nwinkler:  Yeah, I felt like it was becoming somewhat of a daily annoyance & all those seconds add up, so I was quite motivated to get to the bottom of this.

**Comment by nwinkler** [comment]
So what's next? What's the conclusion from this analysis, and what's the recommendation for fixing it?

**Comment by edipox** [comment]
Hi there! I'm facing the same issue.. 
@trinitronx if you disable the stash info does it improve the performance? If that's the case I think the next step would be to apply @trinitronx [patch](https://gist.github.com/trinitronx/2f10d71020c27a76bd1d50c24bfcdb20)  so at least we can improve the performance by disabling the stash information. What do you think @nwinkler ?

**Comment by nwinkler** [comment]
Feel free to open a PR with the change. I would like to see making it optional, though. The default behavior shouldn't change, so we don't break people's current installations.

Please implement a similar flag to some of the others that are currently in use, allowing the user to disable the stash info if they want to.

**Comment by nateharward** [comment]
In case anyone has the same issue, I had a slow prompt where "__powerline_user_info_prompt{}" ended up being the culprit when THEME_CHECK_SUDO=true (as is the default). This function would call sudo -n uptime 2>&1 | grep -q "load"; which sometimes would take several seconds on my work system.

**Comment by kirk86** [comment]
I'm having the exact same issue on Catalina, so fat without any plugin enabled. I'm using the powerline theme. When I disable it things seem to work properly. Any ideas how to resolve this?

**Comment by davidpfarrell** [comment]
> I'm having the exact same issue on Catalina, so fat without any plugin enabled. I'm using the powerline theme. When I disable it things seem to work properly. Any ideas how to resolve this?

Greetings,

The base powerline theme has the following segments defined by default:
```
export POWERLINE_PROMPT="user_info scm python_venv ruby node cwd"
```

I suspect one or more of these segments are taking too long to render on your system.

You might want to try each segment in isolation one at a time to see if you can identify which one(s) are running slower on your system.  

Also if there are any you are not using, just take them out first to see if they were the culprit.

Good luck and please report back with your findings.

-DF

**Comment by kirk86** [comment]
> The base powerline theme has the following segments defined by default:
> 
> ```
> export POWERLINE_PROMPT="user_info scm python_venv ruby node cwd"
> ```
> 
> I suspect one or more of these segments are taking too long to render on your system.

Excellent advise, this solved my problem after removing `scm`. I don't even know what's the purpose of `scm`, but thanks for the tip!

**Comment by nwinkler** [comment]
The `scm` segments shows the SCM (Software Configuration Management) status of the directory you're in. Supported tools are things like Git, Mercurial or Subversion (SVN). These tools allow you to track changes in files, collaborate with other folks on work, etc.

When you had cloned Bash-it, you used Git for that - the Bash-it project is managed using Git. While you're in the Bash-it folder, the `scm` segment will show you the number of local changes, which Git branch you're on, and so on.

It's a powerful feature, but if you're not using anything like Git, then it's perfectly safe to disable this.

**Comment by kirk86** [comment]
Thanks for the info, I'm definitely using git but I don't know why `SCM` would cause this slowness on OSX + iTerm. On my linux box I don't have this problem. Any ideas?

**Comment by nwinkler** [comment]
It really shouldn't, you're right. On bigger repos, it can take significant time, but not on repos like Bash-it.

I'm using Git v2.26.2 on macOS Catalina with Terminal.app. Here's some timing info in the Bash-it repo:

```bash
❯ time git status --porcelain

real	0m0.049s
user	0m0.015s
sys	0m0.026s
```

**Comment by vajdagabor** [comment]
I'm having a similar issue: the next prompt appears after ~2s, **but only in non-scm directories**. Version-managed directories are fine, but when stepping into my home dir or even an empty directory, the prompt needs a few seconds to catch-up.

I tried with a few themes: bobby, clean, powerline, simple…

Turning `scm` off makes things fast again (e.g. `POWERLINE_PROMPT="clock user_info node cwd"`).

_I'm on MacOS 10.15.4 with Homebrew-installed Bash 5.0.17._

**Comment by kirk86** [comment]
@vajdagabor So it's a theme issue right not bash-it related?

**Comment by vajdagabor** [comment]
@kirk86 The culprit was a non-existing SVN on my Mac.

SVN support was removed from XCode 10. The `scm` function in `base.theme.bash` tries running `svn info --show-item wc-root`. On my machine this started an `xcodebuild` process that caused a few seconds long hangup every time I stepped into a non-git directory.

Commenting out that line solved the issue:

```sh
function scm {
  if [[ "$SCM_CHECK" = false ]]; then SCM=$SCM_NONE
  elif [[ -f .git/HEAD ]] && [[ -x "$GIT_EXE" ]]; then SCM=$SCM_GIT
  elif [[ -x "$GIT_EXE" ]] && [[ -n "$(git rev-parse --is-inside-work-tree 2> /dev/null)" ]]; then SCM=$SCM_GIT
  elif [[ -x "$P4_EXE" ]] && [[ -n "$(p4 set P4CLIENT 2> /dev/null)" ]]; then SCM=$SCM_P4
  elif [[ -d .hg ]] && [[ -x "$HG_EXE" ]]; then SCM=$SCM_HG
  elif [[ -x "$HG_EXE" ]] && [[ -n "$(hg root 2> /dev/null)" ]]; then SCM=$SCM_HG
  elif [[ -d .svn ]] && [[ -x "$SVN_EXE" ]]; then SCM=$SCM_SVN
  # elif [[ -x "$SVN_EXE" ]] && [[ -n "$(svn info --show-item wc-root 2>/dev/null)" ]]; then SCM=$SCM_SVN
  else SCM=$SCM_NONE
  fi
}
```

**Comment by nwinkler** [comment]
Thanks for the analysis! To help fixing this (since we obviously can't comment out that line for everyone), can you please provide the following info from your installation?

* What is the output of `which svn`? (I have SVN installed through Homebrew, and it's at `/usr/local/bin/svn`)
* When running the `xcodebuild` that you mention, what's the output of that? What's the output of running `svn info --show-item wc-root` in your Terminal?

We should try to identify the case that you ran into and look at solving that in a different way - or not calling the SVN command in that case.

**Comment by kirk86** [comment]
@vajdagabor That's intersting.
@nwinkler I wonder why using `svn` and not `git`? Most ppl will have git already installed instead of svn.

**Comment by vajdagabor** [comment]
@nwinkler: My pleasure!

The command is located at `/usr/bin/svn`. By running `svn` and `svn info --show-item wc-root` both results in the following message:

```
svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.
```

Clearly, I had the version that was shipped with XCode: https://stackoverflow.com/questions/60869347/mac-command-line-tools-11-4-no-longer-has-svn

**Comment by nwinkler** [comment]
@kirk86 The code checks for all kinds of SCM tools, including Git, SVN, Mercurial, Perforce. If you're in an SVN repo (yes, people still use that), it will show you the repo information for SVN. The purpose of the code is to figure out which kind of repo you're currently in...

**Comment by nwinkler** [comment]
@vajdagabor Have you tried to follow the steps described in this answer to install SVN? https://stackoverflow.com/a/60903732/1228454

The `/usr/bin/svn` command that I have shows v1.13.0 (`/usr/bin/svn --version`).

**Comment by vajdagabor** [comment]
@nwinkler I haven't since I don't use SVN. I am happy to install it with `brew` and see what happens, if that helps.

**Comment by vajdagabor** [comment]
@nwinkler Installed SVN with Brew, restored that line in `base.theme.bash`, and it works nicely now.

**Comment by kirk86** [comment]
> @kirk86 The code checks for all kinds of SCM tools, including Git, SVN, Mercurial, Perforce. If you're in an SVN repo (yes, people still use that), it will show you the repo information for SVN. The purpose of the code is to figure out which kind of repo you're currently in...

@nwinkler That's interesting since all the repos I have are git based and I can confirm what @vajdagabor  was implying that the code for some reason looks for `svn` specifically, after installing `svn` via `brew` things were restored to normal, which indicates that the code by default searches for or uses svn (just a hunch I haven't look into the code in detail)
