### ISSUE TITLE
Where should I put my custom things that don't fit your customization categories?

### ISSUE THREAD

**Issue by GaryFurash** [Bash-it/bash-it#918]
e.g., adding to the path

**Comment by nwinkler** [comment]
Please take a look at the _custom scripts_ section in the README.md: https://github.com/Bash-it/bash-it#your-custom-scripts-aliases-themes-and-functions

Feel free to ask for further info here if that does not help. If this answers your question, please close this issue.

**Comment by nwinkler** [comment]
Closing for now.

**Comment by con-f-use** [comment]
I'm just piggy bagging on this issue to as a related question:

I'm not entirely sure how the custom plugins/aliases/themes work.

What I would like is to specify the custom directory somewhere outside of bash it say `BASH_IT_CUSTOM=~/bi-custom/`. In this custom directory I'd like to add a view alias and plugin files as well as themes (note the plural everywhere). I'd like to be able to activate/deactivate them just as normal, i.e. `bash-it enable alias my_custom_as; bash-it enable alias my_OTHER_custom_as`. They should also be shown when I run `bash-it show aliases`.

It seems to me that this should work. But I'm not sure about the directory structure within my custom dir. Should I put the aliases directly in the dir? Should I put them in a subfolder named `~/bi-custom/aliases/available`? What about the custom themes, plugins and libs?

I'm asking because I tried around a bit and nothing seems to work. Am I doing something stupid or am I just not doing it the canonical way?

**Comment by nwinkler** [comment]
Good question! At the moment, custom components (aliases, completions, plugins) are not included in the whole `enable`/`disable` lifecycle. You can put them in the `custom` directory, and they will be loaded with the rest of Bash-it, but there's no way to enable or disable them on demand through one of Bash-it's commands.

What I suggest you do is this:

* Fork the Bash-it project to your GitHub account.
* Clone your fork locally and install it so that it's used by your shell.
* Add your custom components to the regular Bash-it folders, e.g. add a `con-f-use.aliases.bash` to the regular `$BASH_IT/aliases/available` folder, and then use the regular `bash-it enable alias con-f-use` command to enable them.

You can even commit your custom components this way, you can keep them in your Bash-it fork. If you feel that there is something others would benefit from as well, create a pull request on the main Bash-it repo.

The only thing that's a bit more complex this way is updating from the main Bash-it repo, but than can be scripted as well...

Let me know if this works for you. It sounds like you want to handle your custom components like official Bash-it components, and I think that the fork approach works best for this.

**Comment by con-f-use** [comment]
Okay thanks. Just wanted to make sure this isn't a bug.

I'll probably modify my fork so it searches in the custom dir as well and make a pull request. I think what I want should be the standard behaviour and it wouldn't interfere with automatically sourcing all `*.bash` files in `$BASH_IT_CUSTOM` as it is now. The two can live side by side.

**Comment by nwinkler** [comment]
Thanks! Maybe hold off with changing the search for a moment - I'm in the middle of a refactoring of how loading/enabling/searching works - see #944 for more info. I'm about ready to merge the second half of that, and it will change some of the internal code...

**Comment by con-f-use** [comment]
Will do. Thanks for the heads-up!

**Comment by con-f-use** [comment]
> I'm about ready to merge the second half of that, and it will change some of the internal code...
Did you?

**Comment by nwinkler** [comment]
Sorry, haven't had time for that yet - too busy with other things. I'll try to get it merged in the next couple of days. Sorry again about the delay.
