### ISSUE TITLE
branch name escape char vulnerability

### ISSUE THREAD

**Issue by spieiga** [Bash-it/bash-it#920]
https://news.ycombinator.com/item?id=13897742
https://github.com/njhartwell/pw3nage

at least with osx, not sure on other OS

**Comment by nwinkler** [comment]
Great - thanks for the heads up! Would you like to take a stab at a Pull Request that fixes this?

**Comment by spieiga** [comment]
I'm definitely a n00b with bash so I'm not even sure where to begin.

I think that maybe SCM_BRANCH in themes/base.theme.bash would be what needs fixing, but not sure where else.

The vulnerability author suggests constructing PS1 to reference a variable that holds the branch name.  This is how they fixed it in the official git prompt fix.  https://github.com/git/git/commit/8976500cbbb13270398d3b3e07a17b8cc7bff43f

**Comment by nwinkler** [comment]
I think that would be a good starting point. You could also try replicating the issue to see how Bash-it currently handles the vulnerability. Don't use anything like `rm -rf` of course, but a simple command to show that creating a branch with such a name would trigger the issue when using Bash-it.

Some of it could probably be fixed in the base theme, but some of the other themes use their own functions from what I remember.

**Comment by nwinkler** [comment]
This should now be addressed. @denmat has implemented the white-listing approach, replacing any non-standard characters before the branch name is displayed in the prompt.

Thanks to @denmat and @spieiga for working on this!
