### ISSUE TITLE
Unable to use bash-it programmatically

### ISSUE THREAD

**Issue by ycmjason** [Bash-it/bash-it#960]
I am trying to add the bash-it to my dotfiles installation script.

However, it seems impossible to call bash-it from a script since there isn't a binary for it?

Please guide me on how I could call bash-it from another script.

Thank you.

**Comment by nwinkler** [comment]
Which function of Bash-it do you want to call as part of your dotfiles installation script?

If you're looking for how to enable Bash-it components as part of a script, I've got that covered as part of my own Dotfiles script: https://github.com/nwinkler/dotfiles/blob/master/install_bash_it.sh

You basically need to `source $BASH_IT/bash_it.sh` and can then use the `bash-it enable ...` commands from your script.

Let me know if this helps...

**Comment by ycmjason** [comment]
Thank you for your reply.

I have a `set -e` to make sure my script runs perfectly without an error.

Perhaps `$BASH_IT/bash_it.sh` will cause an internal error which leads to my issue.

**Comment by ycmjason** [comment]
Yup I was correct. So I have done this as a work around:
```
set -e  # make sure that the script abort on error

...

set +e # allow internal error from bash_it.sh
source $BASH_IT/bash_it.sh
set -e # make sure that the script abort on error
bash-it enable plugin extract

...
```

**Comment by nwinkler** [comment]
Thanks for closing!

I'm pretty sure the error is caused by these lines: https://github.com/Bash-it/bash-it/blob/master/bash_it.sh#L85

These should probably be moved to a plugin, same for the Jekyll stuff at the bottom - probably should be in a Jekyll plugin... There's no good reason for these to be in main Bash-it script.

Anybody willing to do a PR to move the _preview_ lines to the `general` plugin, and the Jekyll lines to a dedicated Jekyll plugin?
