### ISSUE TITLE
Docker migration errors

### ISSUE THREAD

**Issue by LanikSJ** [Bash-it/bash-it#985]
This is more of an FYI than anything else since I'm not having any issues.  I saw `bash-it migrate` kick off after i did a `git pull` and `bash-it enable plugin extract` and this is part of the output:
```bash
Migrating docker-compose.bash docker-compose.
_disable-docker-compose.bash: command not found
_enable-docker-compose.bash: command not found
Migrating completion docker-compose.
docker-compose disabled.
docker-compose is already enabled.
Migrating docker-machine.bash docker-machine.
_disable-docker-machine.bash: command not found
_enable-docker-machine.bash: command not found
Migrating completion docker-machine.
docker-machine disabled.
docker-machine is already enabled.
Migrating completion docker.
docker disabled.
docker enabled with priority 350.
```
This is what the completion enabled directory ( `~/.bash_it/completion/enabled` ) looks like:
```bash
350---apm.completion.bash -> ../available/apm.completion.bash
350---awscli.completion.bash -> ../available/awscli.completion.bash
350---bash-it.completion.bash -> ../available/bash-it.completion.bash
350---brew.completion.bash -> ../available/brew.completion.bash
350---bundler.completion.bash -> ../available/bundler.completion.bash
350---defaults.completion.bash -> ../available/defaults.completion.bash
350---dirs.completion.bash -> ../available/dirs.completion.bash
350---docker.completion.bash -> ../available/docker.completion.bash
350---gem.completion.bash -> ../available/gem.completion.bash
350---git.completion.bash -> ../available/git.completion.bash
350---npm.completion.bash -> ../available/npm.completion.bash
350---packer.completion.bash -> ../available/packer.completion.bash
350---pip.completion.bash -> ../available/pip.completion.bash
350---pip3.completion.bash -> ../available/pip3.completion.bash
350---rake.completion.bash -> ../available/rake.completion.bash
350---rvm.completion.bash -> ../available/rvm.completion.bash
350---ssh.completion.bash -> ../available/ssh.completion.bash
350---system.completion.bash -> ../available/system.completion.bash
350---vault.completion.bash -> ../available/vault.completion.bash
docker-compose.completion.bash -> ../available/docker-compose.completion.bash
docker-machine.completion.bash -> ../available/docker-machine.completion.bash
```
I'm running a beta of Docker if that makes any difference.
```bash
97% 2017-06-25 10:51:35 ⌚ |ruby-2.4.1| hostname in ~
○ → docker --version
Docker version 17.06.0-ce-rc5, build b7e4173
```

**Comment by nwinkler** [comment]
Ah, good catch, seems to be caused by #974. Can you please try the following?

```bash
reload

bash-it migrate
```

I think this is caused by the fact that you pulled the changes and then the `migrate` command was run (while enabling something) without having reloaded the changed Bash-it functions.

It should work after running `reload` - please let me know if it does not.

I'm not sure how to permanently fix this. There's a small window where between running a `git pull` and the first `enable/disable` command, if you don't `reload` the changes first, then this issue might happen. Since I've made some major changes to the enable/disable functions in #974, this might happen in this specific case.

**Comment by LanikSJ** [comment]
I know I forgot something!

```bash
97% 2017-06-27 10:06:59 ⌚ |ruby-2.4.1| ierenste02sjl in ~
○ → bash-it migrate
Migrating completion docker-compose.
docker-compose disabled.
docker-compose enabled with priority 350.
Migrating completion docker-machine.
docker-machine disabled.
docker-machine enabled with priority 350.
```

All is good now.

**Comment by nwinkler** [comment]
Thanks for confirming/closing.

It still is an interesting case, where between updating to get a major change like this, and running the `migrate` command, there is some probability of running with an older version of the code. This is caused by the fact that most of the internal work is done by functions, and it will use whatever version of that function is in memory at the moment.

One way to fix it would be to force a reload before running the `migrate` command, but that feels pretty intrusive, and would also slow things down. Not sure how to solve this...

**Comment by LanikSJ** [comment]
What about echo'ing out "Please run reload to apply the changes" or something along those lines when someone runs `bash-it migrate` would that help?

**Comment by nwinkler** [comment]
Yes, I was thinking about something like that as well. Or maybe reload part of the libraries, at least the parts required for migration... I'll think about something before I merge the other half of #944.
