### ISSUE TITLE
Custom aliases breaks alias-completion.plugin.bash

### ISSUE THREAD

**Issue by avoidik** [Bash-it/bash-it#995]
When I start my terminal the input automatically drops into python interactive shell, but before this I see following error message:
```
-bash: complete: /usr/bin/python3: no completion specification
```
Short troubleshooting session point me to **alias-completion.plugin.bash** plugin.

Problematic alias
```
cat ~/.bash_aliases
alias python=/usr/bin/python3
```

Tracing output (CTRL + F - ```no completion specification```):
https://pastebin.com/W22ztCew

**Comment by nwinkler** [comment]
Can you try to define the alias as just this, without the `/usr/bin` part?

```bash
alias python=python3
```

**Comment by avoidik** [comment]
This way it works

**Comment by nwinkler** [comment]
Thanks for confirming! Does this resolve the issue for you? I'm not sure why the `complete` command does not work for commands using a full path...

**Comment by avoidik** [comment]
testcase
```bash
alias_cmd=/usr/bin/python3
alias_name=python
new_completion="$(complete -p "$alias_cmd")"
test_data="${new_completion% *} $alias_name"
echo $test_data
```
should return:
```bash
new_completion='complete -F python /usr/bin/python3'
```
but returns:
```bash
new_completion=' python'
```

then added to $tmp_file:
```bash
echo "$new_completion" >> "$tmp_file"
```

and executed without validations:
```bash
source "$tmp_file" && rm -f "$tmp_file"
```

this way we can inject some malicious code btw :)

**Comment by dracorp** [comment]
Complete works with a full path. True magic is made by command:
```
eval "$completion_loader $alias_cmd"
```
It invokes **_completion_loader** from /usr/share/bash-completion/bash_completion, then it invokes __load_completion function. The last function reduces full path to basename:
```
local OIFS=$IFS IFS=: dir cmd="${1##*/}" compfile
```
and works on it.
For example for /usr/bin/python.
Function __load_completion sources /usr/share//bash-completion/completions/python and returns 0 to _completion_loader. _completion_loader returns 124 to plugins/available/alias-completion.plugin.bash.
But:
```
$ complete -p /usr/bin/python
bash: complete: /usr/bin/python: no completion specification
$ complete -p | grep python
complete -F _python py
complete -F _python pypy
complete -F _python python2
complete -F _python python3
complete -F _python python
complete -F _python pypy3
complete -F _minimal ipython
complete -F _python micropython
```
For /usr/bin/vim array ${_xspecs[$cmd]} is not empty and it is equal:
```
*.@([ao]|so|so.!(conf|*/*)|[rs]pm|gif|jp?(e)g|mp3|mp?(e)g|avi|asf|ogg|class)
```
So for /usr/bin/vim it invokes:
```
complete -F _filedir_xspec vim
```
and returns 0 to _completion_loader, and later 124 to alias-completion.plugin.bash so it works.
But again:
```
$ complete -p /usr/bin/vim
bash: complete: /usr/bin/vim: no completion specification
```
But for /usr/bin/xclip (an alias from clipboard.aliases.bash) it invokes:
```
complete -F _minimal -- /usr/bin/xclip
```
because __load_completion has returned 1 (false).

I think that basename should always go to _completion_loader ($completion_loader).

**Comment by dracorp** [comment]
Last but not least. For example, in my company people use alias: `alias vim='/usr/bin/vim -X` so:
```
$ command -v vim
alias vim='/usr/bin/vim -X'
$ which vim
alias vim='/usr/bin/vim -X'
        /usr/bin/vim
```
This is on CentOS 7.4, while on another CentOS:
```
$ command -v vim
alias vim='/usr/bin/vim -X'
$ which vim
/usr/bin/vim
```
Strange...
Maybe each alias should also be defined with basename command. For example for aliases/available/vim.aliases.bash:
```
VIM=$(command -v vim | xargs --no-run-if-empty basename)
```
then
```
$ alias v
alias v='vim'
$ complete -p v
complete -F _filedir_xspec v
```

**Comment by NoahGorny** [comment]
This issue is very stale, so I close it. Thanks for contributing and posting!
